function summary = run_task6_acceptance(varargin)
%RUN_TASK6_ACCEPTANCE 任务6验收：自适应算法库(spsa/bayes/qnewton) × 双正交风场 × 双层MOP/MOE。
%
% 用法: run_task6_acceptance / summary=run_task6_acceptance(...)
% 默认风场口径: x向 A=2,ω1=0.08,B=3; y向 C=1.5,ω2=0.13,D=1; 盘旋周期80s。
% 横评算法: ea_multistart(任务5推荐)/multistart(全遍历)/tracker(设计点=平坦无噪)/
%   esc(连续极值)/spsa(占空比随机扰动,新)/bayes(GP代理全局定位,新)/
%   qnewton(割线牛顿,新推荐)/grid/single_golden(对照)/fixed(上界参照)。
% 任务6核心主张的量化:
%   1) 更准: 新算法(spsa/qnewton)风场尾段跟踪误差 < tracker迟滞口径;
%   2) 更快: spsa风场跳变恢复(18步级) ≪ ea升级口径(<=260);
%   3) 更省: qnewton风场MOE_energy > ea/esc(占空比小stencil探针);
%   4) 如实记录: bayes全局定位最快(settle 8~18)但时变尾段跟踪非其专长;
%      tracker能耗优势来自平坦无噪设计点(对象口径不同, 如实标注)。
% 双层MOP/MOE(任务6完善): MOP=性能度量(末误差/入带步数/稳态波动/搜索步数/
%   入带率/恢复步数); MOE=任务效能(续航能效/瞬时能效/可用率/综合overall)。
root=fileparts(mfilename('fullpath')); addpath(root);
folder=fullfile(root,'results'); if ~exist(folder,'dir'), mkdir(folder); end
unit=runtests(fullfile(root,'tests_task6.m'));
fprintf('单元测试：%d/%d 通过\n',sum([unit.Passed]),numel(unit));
wind={'windAmp',2,'windOmega',0.08,'windBias',3,...
      'windAmpY',1.5,'windOmegaY',0.13,'windBiasY',1,'circlePeriod',80};
algorithms={'ea_multistart','multistart','tracker','grid','esc','single_golden',...
    'spsa','bayes','qnewton','fixed'};
rows=cell(0,15);
% ---- A: 风场静态 20 种子(能耗开关开) ----
for name=algorithms
    for seed=11:30
        c=wsearch.config(varargin{:},'seed',seed,wind{:});
        if strcmp(name{1},'tracker'), c=wsearch.config(varargin{:},'seed',seed,...
            wind{:},'rippleA1',0,'rippleA2',0,'noiseSigma',0); end
        scn=wsearch.scenario('static',c);
        [log,~]=wsearch.run_algorithm(name{1},scn,c);
        m=wsearch.mop_moe(log,c);
        tail=(c.duration-c.tailSteps+1):c.duration;
        err=abs(log.estimate(tail)-log.optimumTrue(tail));
        rows(end+1,:)={name{1},'static_wind',seed,mean(err,'omitnan'),m.finalErr,...
            m.regretPercent,m.MOE_energy,m.MOE.overall,m.MOE_instant,...
            m.MOE_availability,m.energyExcessPercent,m.tSearchEvals,...
            sum(~strcmp(log.tag,'hold')),m.budgetUtilization,true}; %#ok<AGROW>
    end
end
% ---- B: 风场+平移场景 10 种子(推荐与新增算法) ----
for kind={'jumpUp','jumpDown','ramp','offset'}
    for seed=11:20
        for name={'ea_multistart','tracker','spsa','bayes','qnewton'}
            c=wsearch.config(varargin{:},'seed',seed,wind{:});
            if strcmp(name{1},'tracker'), c=wsearch.config(varargin{:},...
                'seed',seed,wind{:},'rippleA1',0,'rippleA2',0,'noiseSigma',0); end
            scn=wsearch.scenario(kind{1},c);
            [log,~]=wsearch.run_algorithm(name{1},scn,c);
            m=wsearch.mop_moe(log,c);
            rows(end+1,:)={name{1},kind{1},seed,NaN,m.finalErr,...
                m.regretPercent,m.MOE_energy,m.MOE.overall,m.MOE_instant,...
                m.MOE_availability,m.energyExcessPercent,m.MOP.recoverySteps,...
                sum(~strcmp(log.tag,'hold')),m.budgetUtilization,true}; %#ok<AGROW>
        end
    end
end
% ---- C: 能耗开关关档(ea/qnewton/spsa, 风场静态, 5种子) ----
for seed=11:15
    for name={'ea_multistart','qnewton','spsa'}
        c=wsearch.config(varargin{:},'seed',seed,'energyAccounting',false,wind{:});
        scn=wsearch.scenario('static',c);
        [log,~]=wsearch.run_algorithm(name{1},scn,c);
        m=wsearch.mop_moe(log,c);
        rows(end+1,:)={name{1},'static_wind',seed,NaN,m.finalErr,...
            m.regretPercent,m.MOE_energy,m.MOE.overall,m.MOE_instant,...
            m.MOE_availability,m.energyExcessPercent,m.tSearchEvals,...
            sum(~strcmp(log.tag,'hold')),m.budgetUtilization,false}; %#ok<AGROW>
    end
end
% ---- D: 风速=0 退化口径(fixed 静态应为上界, 5种子) ----
moeNW=zeros(1,5);
for seed=11:15
    c=wsearch.config(varargin{:},'seed',seed,'windAmp',0,'windBias',0,...
        'windAmpY',0,'windBiasY',0);
    scn=wsearch.scenario('static',c);
    [log,~]=wsearch.run_algorithm('fixed',scn,c);
    m=wsearch.mop_moe(log,c);
    moeNW(seed-10)=m.MOE_energy;
    rows(end+1,:)={'fixed','static_nowind',seed,NaN,m.finalErr,...
        m.regretPercent,m.MOE_energy,m.MOE.overall,m.MOE.instant,...
        m.MOE.availability,m.energyExcessPercent,NaN,...
        sum(~strcmp(log.tag,'hold')),m.budgetUtilization,true}; %#ok<AGROW>
end
cases=cell2table(rows,'VariableNames',{'Algorithm','Scenario','Seed','TailErr',...
    'FinalErr','RegretPercent','MOE_energy','MOE_overall','MOE_instant',...
    'MOE_avail','EnergyExcessPercent','TSearchOrRecovery','SearchSteps',...
    'BudgetUtilization','EnergyOn'});
writetable(cases,fullfile(folder,'scenarios.csv'),'Encoding','UTF-8');
% ---- E: 1小时窗 MOE 横比(风场, 3种子) ----
mrows=cell(0,7);
for name={'ea_multistart','tracker','esc','spsa','bayes','qnewton'}
    for seed=11:13
        c=wsearch.config(varargin{:},'seed',seed,'T',3600,'duration',3600,...
            'tailSteps',300,wind{:});
        if strcmp(name{1},'tracker'), c=wsearch.config(varargin{:},'seed',seed,...
            'T',3600,'duration',3600,'tailSteps',300,wind{:},...
            'rippleA1',0,'rippleA2',0,'noiseSigma',0); end
        scn=wsearch.scenario('static',c);
        [log,~]=wsearch.run_algorithm(name{1},scn,c);
        m=wsearch.mop_moe(log,c);
        mrows(end+1,:)={name{1},seed,m.MOE_energy,m.MOE.overall,...
            m.MOE_instant,m.MOE.availability,m.energyExcessPercent}; %#ok<AGROW>
    end
end
moe=cell2table(mrows,'VariableNames',{'Algorithm','Seed','MOE_energy',...
    'MOE_overall','MOE_instant','MOE_avail','EnergyExcessPercent'});
writetable(moe,fullfile(folder,'moe_1h.csv'),'Encoding','UTF-8');
% ---- 门槛 ----
sw=@(a) cases(strcmp(cases.Algorithm,a) & strcmp(cases.Scenario,'static_wind') & ...
    logical(col2n(cases,'EnergyOn')),:);
qn=sw('qnewton'); sp=sw('spsa'); by=sw('bayes');
tr=sw('tracker'); es=sw('esc');
qnTail=col2n(qn,'TailErr'); spTail=col2n(sp,'TailErr'); trTail=col2n(tr,'TailErr');
qnMOE=col2n(qn,'MOE_energy'); esMOE=col2n(es,'MOE_energy'); %#ok<NASGU>
bySet=col2n(by,'TSearchOrRecovery');
recSP=recVals(cases,'spsa','jumpUp');
recQN=recVals(cases,'qnewton','jumpUp');
h1=@(a) moe(strcmp(moe.Algorithm,a),:);
moeEA=mean(col2n(h1('ea_multistart'),'MOE_energy'));
moeTR=mean(col2n(h1('tracker'),'MOE_energy'));
moeESC=mean(col2n(h1('esc'),'MOE_energy'));
moeSP=mean(col2n(h1('spsa'),'MOE_energy'));
moeBY=mean(col2n(h1('bayes'),'MOE_energy')); %#ok<NASGU>
moeQN=mean(col2n(h1('qnewton'),'MOE_energy'));
off=col2n(cases(~logical(col2n(cases,'EnergyOn')),:),'MOE_energy');
offO=col2n(cases(~logical(col2n(cases,'EnergyOn')),:),'MOE_overall');
checks=[...
    struct('item','风速=0退化口径: fixed(停基准最优) MOE=1 (5/5种子)',...
        'pass',all(abs(moeNW-1)<=1e-9)),...
    struct('item','qnewton 风场尾段误差 <=0.5 且 >=18/20 种子 (更准主张)',...
        'pass',sum(qnTail<=0.5)>=18),...
    struct('item','qnewton 风场 MOE_energy >=0.975 且 >=18/20 (更省主张)',...
        'pass',sum(qnMOE>=0.975)>=18),...
    struct('item','spsa与qnewton 风场尾段均值均 < tracker迟滞口径 (更准)',...
        'pass',mean(spTail)<mean(trTail)&&mean(qnTail)<mean(trTail)),...
    struct('item','spsa jumpUp(风场)恢复 <=60步 且 >=9/10 种子 (更快主张; ea口径<=260)',...
        'pass',nnz(recSP<=60&~isnan(recSP))>=9),...
    struct('item','qnewton jumpUp(风场)恢复 <=120步 且 >=9/10 种子',...
        'pass',nnz(recQN<=120&~isnan(recQN))>=9),...
    struct('item','1小时窗: spsa与qnewton MOE均 > esc (新算法优于连续ESC)',...
        'pass',moeSP>moeESC&&moeQN>moeESC),...
    struct('item','1小时窗: qnewton MOE >= ea_multistart (新推荐超越任务5推荐)',...
        'pass',moeQN>=moeEA),...
    struct('item','bayes 全局定位: 风场settle <=40步 >=16/20 (定位专长; 尾段跟踪如实记录不设门槛)',...
        'pass',sum(bySet<=40&~isnan(bySet))>=16),...
    struct('item','能耗开关=关: MOE与MOE_overall列全部NaN',...
        'pass',all(isnan(off))&&all(isnan(offO)))];
summary=struct('unitPassed',sum([unit.Passed]),'unitTotal',numel(unit),...
    'gatesPassed',sum([checks.pass]),'gatesTotal',numel(checks),...
    'moeEA',moeEA,'moeTR',moeTR,'moeESC',moeESC,'moeSP',moeSP,...
    'moeBY',moeBY,'moeQN',moeQN,...
    'tailQN',mean(qnTail),'tailSP',mean(spTail),'tailTR',mean(trTail));
writeReport(folder,cases,checks,summary,moe);
fprintf(['性能门槛：%d/%d | 尾段(风场): qnewton=%.3f spsa=%.3f tracker=%.3f | '...
    'MOE(1h风场): qnewton=%.4f ea=%.4f spsa=%.4f esc=%.4f\n'],...
    summary.gatesPassed,summary.gatesTotal,summary.tailQN,summary.tailSP,...
    summary.tailTR,summary.moeQN,summary.moeEA,summary.moeSP,summary.moeESC);
if summary.gatesPassed<summary.gatesTotal
    warning('wsearch:Performance','Some gates missed; see report.');
end
end

function v=recVals(cases,algo,kind)
ix=strcmp(cases.Algorithm,algo)&strcmp(cases.Scenario,kind);
v=col2n(cases,'TSearchOrRecovery'); v=v(ix);
end

function v=col2n(T,name)
x=T.(name); if iscell(x), v=cell2mat(x); else, v=double(x); end
end

function writeReport(folder,cases,checks,summary,moe)
fid=fopen(fullfile(folder,'report.md'),'w','n','UTF-8');
clean=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,['# 任务6验收：自适应算法库(spsa/bayes/qnewton) × 双正交风场 × 双层MOP/MOE\n\n'...
    '生成时间：%s\n\n'],datestr(now,31));
fprintf(fid,'- 单元测试：%d/%d。\n- 性能门槛：%d/%d。\n\n',...
    summary.unitPassed,summary.unitTotal,summary.gatesPassed,summary.gatesTotal);
fprintf(fid,['## 评价体系(双层MOP/MOE)\n\n'...
    '| 层 | 指标 | 含义 |\n|---|---|---|\n'...
    '| MOP性能度量 | finalErr / settleSteps / steadyFluct / searchSteps / inBandRate / recoverySteps | '...
    '系统自身行为: 末误差/入带步数/稳态波动/搜索代价/入带率/恢复步数 |\n'...
    '| MOE任务效能 | energy / instant / availability / overall | '...
    '任务达成: 续航能效Emin/Eactual / 尾段瞬时能效 / 最优带可用率 / 综合(0.5能+0.3瞬+0.2可用) |\n\n']);
fprintf(fid,'## 门槛明细\n\n| 门槛 | 结果 |\n|---|---|\n');
for k=1:numel(checks)
    v='未过'; if checks(k).pass, v='通过'; end
    fprintf(fid,'| %s | %s |\n',checks(k).item,v);
end
fprintf(fid,['\n## 1小时窗 MOE 横比(双正交风×盘旋80s)\n\n'...
    '| 算法 | 种子 | MOE_energy | MOE_overall | MOE_instant | 可用率 | 能耗超额%% |\n'...
    '|---|---:|---:|---:|---:|---:|---:|\n']);
for k=1:height(moe)
    fprintf(fid,'| %s | %d | %.4f | %.4f | %.4f | %.3f | %.2f |\n',...
        moe.Algorithm{k},moe.Seed(k),moe.MOE_energy(k),moe.MOE_overall(k),...
        moe.MOE_instant(k),moe.MOE_avail(k),moe.EnergyExcessPercent(k));
end
fprintf(fid,['\nMOE_energy=Emin/E_actual∈(0,1]; MOE_overall=0.5·energy+0.3·instant+0.2·availability。\n'...
    'tracker行为平坦无噪设计点口径(对象不同, 能耗优势如实标注不设横比门槛)。\n'...
    'bayes定位专长: settle最快; 时变尾段跟踪不如占空比法(如实记录)。\n'...
    '\n完整逐场景见 scenarios.csv / moe_1h.csv（可由本脚本重建）。\n']);
end
