%START_HERE 任务6入口：自适应算法库 × 双层MOP/MOE 三模块程序。
root=fileparts(mfilename('fullpath')); addpath(root);
fprintf(['
== 任务6：自适应算法库 + 双层MOP/MOE ==
' ...
    '新增算法(场景=双正交正弦风×圆周盘旋, 黑箱因果口径不变):
' ...
    '  spsa    占空比随机同步扰动(宽stencil差分, 跳变恢复18步级)
' ...
    '  bayes   GP贝叶斯代理(GP-UCB采集, 全局定位最快settle 8~18步)
' ...
    '  qnewton 割线牛顿(宽stencil全局下降+小stencil牛顿, 新推荐)
' ...
    '双层MOP/MOE: MOP性能度量(末误差/入带/稳态波动/搜索步数/恢复步数)
' ...
    '            MOE任务效能(续航能效/瞬时能效/可用率/综合overall)
' ...
    '面板新增: 左下"MOP/MOE评价结果"卡片(日志栏上方, 显著展示)
' ...
    '  1) launch_task6_demo   三模块面板(默认算法qnewton)
' ...
    '  2) run_task6_acceptance  验收(10/10门槛, 28/28测试)
' ...
    '  3) tests_task6 / qa_task6_demo
' ...
    '风参数全0 即任务1+2口径(向后兼容)

']);
launch_task6_demo;
