function c = config(varargin)
%CONFIG Residual speed-RL settings. Values are simulation, not flight limits.
c=struct('Ts',0.05,'decisionPeriod',1,'duration',120,'history',8,'seed',1,...
    'training',false,'randomizeWind',false,'windMode','irregular','windObservation','observable','powerDropouts',false,...
    'trajectory','straight','speedBounds',[2 15],'deltaBounds',[-3 3],...
    'initialSpeed',6.3,'baselineSpeed',6.3,'speedRate',0.5,'tauSpeed',1,...
    'optimumAirSpeed',6.3,'powerScale',500,'powerNoiseFraction',0.02,...
    'powerDelay',0.5,'maxPowerAge',1,'windNoiseStd',0.15,'windDelay',0.2,'maxWindAge',2,...
    'capacityAh',8,'internalResistance',0.04,'initialSoc',0.85,...
    'minimumVoltage',18,'pathRadius',30,'radialFreeze',5,'radialScale',5,...
    'usableEnergyWh',150,'movePenalty',0.002,'missingPenalty',10,...
    'blockedPenalty',10,'trajectoryPenalty',2,'constantWind',[2;-1],...
    'ouTimeConstant',12,'ouStd',2,'gustProbability',0.004,'gustMagnitude',3);
assert(mod(nargin,2)==0,'speedrl:Config','Use name/value pairs.');
for k=1:2:nargin
    key=char(varargin{k}); assert(isfield(c,key),'speedrl:Config','Unknown setting: %s',key);
    c.(key)=varargin{k+1};
end
assert(any(strcmp(c.windMode,{'none','constant','step','sine','irregular','mixed'})),...
    'speedrl:Config','Unknown windMode.');
assert(any(strcmp(c.windObservation,{'observable','dropout','hidden'})),...
    'speedrl:Config','Unknown windObservation.');
assert(any(strcmp(c.trajectory,{'straight','circle'})),'speedrl:Config','Unknown trajectory.');
assert(islogical(c.training) && isscalar(c.training) && islogical(c.randomizeWind) && isscalar(c.randomizeWind) && ...
    islogical(c.powerDropouts) && isscalar(c.powerDropouts),...
    'speedrl:Config','Boolean switches must be logical scalars.');
positive={'Ts','decisionPeriod','duration','history','speedRate','tauSpeed',...
    'optimumAirSpeed','powerScale','maxPowerAge','maxWindAge','capacityAh','minimumVoltage',...
    'pathRadius','radialFreeze','radialScale','usableEnergyWh','ouTimeConstant','ouStd','gustMagnitude'};
for k=1:numel(positive)
    validateattributes(c.(positive{k}),{'double'},{'scalar','real','finite','positive'});
end
nonnegative={'powerNoiseFraction','powerDelay','windNoiseStd','windDelay',...
    'internalResistance','movePenalty','missingPenalty','blockedPenalty','trajectoryPenalty','gustProbability'};
for k=1:numel(nonnegative)
    validateattributes(c.(nonnegative{k}),{'double'},{'scalar','real','finite','nonnegative'});
end
validateattributes(c.seed,{'double'},{'scalar','integer','>=',0,'<=',2^32-1});
assert(c.history==round(c.history) && c.history<=32,'speedrl:Config','Invalid history length.');
for name={'speedBounds','deltaBounds'}
    b=c.(name{1}); validateattributes(b,{'double'},{'vector','numel',2,'real','finite'});
    assert(b(1)<b(2),'speedrl:Config','Bounds must increase.');
end
validateattributes(c.constantWind,{'double'},{'size',[2 1],'real','finite'});
validateattributes(c.initialSoc,{'double'},{'scalar','>',0,'<=',1});
validateattributes(c.gustProbability,{'double'},{'scalar','<=',1});
assert(c.initialSpeed>=c.speedBounds(1) && c.initialSpeed<=c.speedBounds(2),...
    'speedrl:Config','Initial speed outside bounds.');
assert(c.baselineSpeed>=c.speedBounds(1) && c.baselineSpeed<=c.speedBounds(2),...
    'speedrl:Config','Baseline speed outside bounds.');
ratios=[c.duration/c.decisionPeriod,c.decisionPeriod/c.Ts,c.powerDelay/c.Ts,c.windDelay/c.Ts];
assert(all(abs(ratios-round(ratios))<1e-8),'speedrl:Config','Periods must be integer sample multiples.');
assert(c.maxWindAge>=c.windDelay,'speedrl:Config','maxWindAge must cover windDelay.');
end
