function stages = curriculum(duration)
%CURRICULUM Increasing disturbance and observability difficulty.
if nargin<1, duration=120; end
spec={...
    'calm','none','observable','straight';...
    'constant','constant','observable','straight';...
    'step','step','observable','straight';...
    'circle_sine','sine','observable','circle';...
    'irregular_visible','irregular','observable','circle';...
    'irregular_dropout','irregular','dropout','circle';...
    'irregular_hidden','irregular','hidden','circle'};
stages=cell(size(spec,1),1);
for k=1:size(spec,1)
    stages{k}=speedrl.config('duration',duration,'windMode',spec{k,2},...
        'windObservation',spec{k,3},'trajectory',spec{k,4},'randomizeWind',true,'seed',1000+100*k);
    stages{k}.stageName=spec{k,1};
end
end
