function [observation,history,frame] = observe(ctx,history,c)
%OBSERVE Fixed scales and masks keep the interface stable across adapters.
b=c.speedBounds; d=max(abs(c.deltaBounds));
frame=[ctx.groundSpeed/b(2);ctx.airSpeed/20;...
    (ctx.reference-b(1))/diff(b);(ctx.baseSpeed-b(1))/diff(b);ctx.lastDelta/d;...
    ctx.meanPower/c.powerScale;ctx.deltaPower/c.powerScale;...
    ctx.windAlong/10;ctx.windNormal/10;ctx.windAge/c.maxWindAge;...
    ctx.soc;ctx.voltage/25.2;sin(ctx.phase);cos(ctx.phase);...
    ctx.radialError/c.radialScale;ctx.velocityValid;ctx.powerValid;ctx.windValid];
frame(~isfinite(frame))=0; frame=max(min(frame,5),-5);
if isempty(history), history=repmat(frame,1,c.history);
else, history=[history(:,2:end),frame]; end
observation=history(:);
end
