function names = observation_names()
names={'ground_speed','air_speed','speed_reference','baseline_speed','last_residual',...
    'mean_power','power_change','wind_tangent','wind_normal','wind_age','soc','voltage',...
    'sin_path_phase','cos_path_phase','radial_error','velocity_valid','power_valid','wind_valid'};
end
