%START_HERE 任务3入口：环境(恒定风×圆周盘旋) × 崎岖对象 × MOP/MOE。
root=fileparts(mfilename('fullpath')); addpath(root);
fprintf(['\n== 任务3：风场圆周寻优 ==\n' ...
    '环境模型: 恒定风矢量 × 匀速盘旋(航向 psi(t)=2*pi*t/T)\n' ...
    '          逆风半圈最优空速增大/功率升高, 顺风半圈相反(周期性偏移)\n' ...
    '  1) launch_task3_demo   动画面板(风速/盘旋周期/场景/平移参数在线可调)\n' ...
    '  2) run_task3_acceptance  验收(测试+门槛)\n' ...
    '  3) tests_task3 / qa_task3_demo\n' ...
    'MOP/MOE: MOE_energy=Emin/E_actual(1小时窗), 7项MOP\n' ...
    '搜索能耗开关: wsearch.config(''energyAccounting'',true/false)\n' ...
    '风速=0 即任务1+2口径(向后兼容)\n\n']);
launch_task3_demo;
