function rows = m7_rows(chunkId, arm, m, runS)
%Q39.M7_ROWS M7 记账行展开: 每臂三行 true / est / diff(QUAD_MIGRATION_PLAN §5-M7
% "true/estimated 两口径列 + 差值行")。diff 行的 excess/moe/margin 列即双口径差值
% (与 delta_* 列数值一致, 供无列语义的机器核对)。
f = struct('chunk', {chunkId, chunkId, chunkId}, ...
    'arm', {arm, arm, [arm '__diff']}, ...
    'caliber', {'true', 'est', 'diff'}, ...
    'excess_pct', {m.excess_true_pct, m.excess_est_pct, m.delta_excess_pp}, ...
    'moe', {m.moe_true, m.moe_est, m.moe_true - m.moe_est}, ...
    'margin_pp', {m.margin_true_pp, m.margin_est_pp, m.delta_margin_pp}, ...
    'delta_excess_pp', {m.delta_excess_pp, m.delta_excess_pp, m.delta_excess_pp}, ...
    'delta_margin_pp', {m.delta_margin_pp, m.delta_margin_pp, m.delta_margin_pp}, ...
    'bias_meas_pct', {m.bias_meas_pct, m.bias_meas_pct, m.bias_meas_pct}, ...
    'rowsN', {m.rowsN, m.rowsN, m.rowsN}, ...
    'runtime_s', {runS, runS, runS});
rows = f;
end
