function c = config(varargin)
%CONFIG Harness settings for MOP/MOE evaluation over a fixed mission window.
% 与路线图表4/统一接口合同一致：评价器在对象侧，控制器侧只进白名单。
c=struct('T',3600,'tEval',1.0,'lower',0,'upper',20,'optimum0',6,...
    'rippleA1',0.022,'rippleL1',6.0,'rippleF1',pi,...
    'rippleA2',0.012,'rippleL2',2.0,'rippleF2',pi,...
    'noiseSigma',0.01,'impulse',false,'impulseRate',0.03,'impulseSize',0.10,...
    'seed',1,'powerScaleW',100,...
    'tol',0.02,'maxSearchEval',60,'scanN',61,'filterMethod','sg','filterW',7,...
    'K',5,'minSep',1.5,'refineSpan',0.7,'repeats',3,'initialSpeed',10,...
    'escA',0.5,'escOmega',0.5,'escGain',8,'escLpOmega',0.5,'escWindow',7,...
    'gridResolution',0.125);
assert(mod(nargin,2)==0,'harness:Config','Use name/value pairs.');
for k=1:2:nargin
    key=char(varargin{k}); assert(isfield(c,key),'harness:Config','Unknown setting: %s',key);
    c.(key)=varargin{k+1};
end
assert(islogical(c.impulse) && isscalar(c.impulse),'harness:Config','impulse must be logical.');
positive={'T','tEval','lower','upper','optimum0','rippleA1','rippleL1','rippleA2',...
    'rippleL2','noiseSigma','impulseRate','impulseSize','seed','powerScaleW'};
for k=1:numel(positive), validateattributes(c.(positive{k}),{'double'},...
    {'scalar','real','finite','nonnegative'}); end
assert(c.upper>c.lower && c.optimum0>=c.lower && c.optimum0<=c.upper,...
    'harness:Config','Invalid bounds/optimum.');
assert(c.T>c.tEval && mod(c.T,c.tEval)<1e-9,'harness:Config','T must be integer multiple of tEval.');
end
