function c = config(varargin)
%CONFIG 统一速度寻优程序设置：崎岖调试曲线 + 可控平移 + MOP/MOE评价窗。
c=struct('lower',0,'upper',20,'optimum0',6,...
    'rippleA1',0.022,'rippleL1',6.0,'rippleF1',pi,...
    'rippleA2',0.012,'rippleL2',2.0,'rippleF2',pi,...
    'noiseSigma',0.01,'impulse',false,'impulseRate',0.03,'impulseSize',0.10,...
    'tEval',1.0,'duration',400,'T',400,'tailSteps',60,'seed',1,...
    'tol',0.02,'maxSearchEval',60,'eps',0.4,...
    'initialSpeed',10,...
    'shiftTime',120,'jumpUpDx',2.7,'jumpDownDx',-2.3,'dyOffset',0.05,...
    'rampStart',60,'rampEnd',180,'rampDx',1.7,...  % multistart基线参数在下方
    'scanN',61,'filterMethod','sg','filterW',7,'K',5,'minSep',1.5,...
    'refineSpan',0.7,'repeats',4,...
    't1ProbeDelta',0.5,'t1ProbePeriod',10,'t1SlopeThresh',0.002,...
    't1SlopeRelease',0.0005,'t1Span0',3.0,'t1Grow',2.0,'t1Retry',2,...
    'eaLocalW0',0.35,'eaLocalW1',0.2,'eaFarProbes',3,'eaFarRepeats',2,...
    'eaSigmaRepeats',4,'eaMarginSigma',2.5,'eaScanN',41,'eaK',3,...
    'eaPolishRepeats',4,'probePeriod',12,'probeDelta',1.0,'probeRepeats',2,...
    'slopeThresh',0.02,'relocalMax',3,...
    'escA',0.5,'escOmega',0.5,'escGain',8,'escLpOmega',0.5,'escWindow',7,...
    'gridResolution',0.125,...
    'energyAccounting',true);
assert(mod(nargin,2)==0,'usearch:Config','Use name/value pairs.');
for k=1:2:nargin
    key=char(varargin{k}); assert(isfield(c,key),'usearch:Config','Unknown setting: %s',key);
    c.(key)=varargin{k+1};
end
assert(islogical(c.energyAccounting) && isscalar(c.energyAccounting),...
    'usearch:Config','energyAccounting must be logical.');
assert(islogical(c.impulse) && isscalar(c.impulse),'usearch:Config','impulse must be logical.');
positive={'tEval','duration','T','tailSteps','tol','maxSearchEval','eps','initialSpeed',...
    'shiftTime','dyOffset','rampStart','rampEnd','rampDx',...
    'rippleA1','rippleL1','rippleA2','rippleL2','noiseSigma','impulseRate','impulseSize',...
    'scanN','filterW','K','minSep','refineSpan','repeats',...
    't1ProbeDelta','t1ProbePeriod','t1SlopeThresh','t1SlopeRelease','t1Span0','t1Grow','t1Retry',...
    'eaLocalW0','eaLocalW1','eaFarProbes','eaFarRepeats','eaSigmaRepeats','eaMarginSigma',...
    'eaScanN','eaK','eaPolishRepeats','probePeriod','probeDelta','probeRepeats',...
    'slopeThresh','relocalMax','escA','escOmega','escGain','escLpOmega','escWindow',...
    'gridResolution','seed'};
for k=1:numel(positive), validateattributes(c.(positive{k}),{'double'},...
    {'scalar','real','finite','nonnegative'}); end
signed={'jumpUpDx','jumpDownDx'};
for k=1:numel(signed), validateattributes(c.(signed{k}),{'double'},{'scalar','real','finite'}); end
assert(c.lower>=0 && c.upper>c.lower && c.optimum0>=c.lower && c.optimum0<=c.upper,...
    'usearch:Config','Invalid bounds/optimum.');
assert(c.initialSpeed>=c.lower && c.initialSpeed<=c.upper,'usearch:Config','Initial speed outside bounds.');
assert(mod(c.filterW,2)==1 && c.filterW>=3,'usearch:Config','filterW must be odd >=3.');
assert(c.duration>c.tailSteps && c.duration>=c.scanN,'usearch:Config','duration too short.');
assert(c.t1SlopeRelease<c.t1SlopeThresh,'usearch:Config','t1SlopeRelease<t1SlopeThresh required.');
assert(c.t1ProbeDelta>0 && 2*c.t1ProbeDelta<c.upper-c.lower,'usearch:Config','Invalid t1ProbeDelta.');
assert(c.probeDelta>0 && 2*c.probeDelta<c.upper-c.lower,'usearch:Config','Invalid probeDelta.');
assert(c.eaScanN>=11 && c.eaScanN<=501,'usearch:Config','eaScanN out of range.');
assert(c.shiftTime<c.duration-c.tailSteps,'usearch:Config','shiftTime must leave evaluation tail.');
assert(c.rampEnd>c.rampStart,'usearch:Config','rampEnd>rampStart required.');
end
