function c = config(varargin)
%PLANE.CONFIG P0-P4 unified Plane proxy configuration (uncalibrated).
c=struct('schema_version','0.3','plane_model_id','plane_proxy_p0p4_v2',...
 'power_model_id','joint_proxy_v1',...
 'sample_time_s',0.01,'speed_tau_s',1.0,'eta_tau_s',0.5,...
 'speed_bounds_mps',[0 20],'speed_rate_mps2',2.0,'eta_bounds',[0.75 1.25],...
 'eta_rate_s',0.10,'circle_radius_m',20,'mass_kg',1.4,'gravity_mps2',9.81,...
 'hover_power_W',251,'speed_power_gain_W_per_mps2',1.8,'eta_power_gain_W',80,...
 'drag_power_gain_W_per_mps2',0.35,'battery_capacity_Ah',5,'battery_full_V',25.2,...
 'battery_empty_V',19.2,'battery_cutoff_V',18,'battery_resistance_ohm',0.08,...
 'aux_power_W',12,'battery_efficiency',0.95,'max_power_W',1500,...
 'altitude_m',10,'altitude_ref_m',10,'altitude_tol_m',1.0,'radial_tol_m',2.0,...
 'attitude_tol_rad',0.523,'yaw_rate_tol_radps',1.5);
if mod(numel(varargin),2)~=0,error('plane:Config','Use name/value pairs.');end
for k=1:2:numel(varargin),n=char(varargin{k});if ~isfield(c,n),error('plane:Config','Unknown parameter %s',n);end;c.(n)=varargin{k+1};end
assert(c.speed_tau_s>0&&c.eta_tau_s>0&&c.battery_capacity_Ah>0,'plane:Config','Invalid time/battery parameters.');
assert(c.speed_bounds_mps(1)<c.speed_bounds_mps(2)&&c.eta_bounds(1)<c.eta_bounds(2),'plane:Config','Invalid bounds.');
end
