function [s,sample]=reset(c,initial)
%PLANE.RESET Reset with self-consistent speed, eta and battery state.
if nargin<1||isempty(c),c=plane.config();end;if nargin<2,initial=struct();end
s=struct('time_s',0,'position_ne_m',[c.circle_radius_m;0],'altitude_m',c.altitude_m,...
 'ground_velocity_ne_mps',[0;0],'v_ground_mps',0,'v_ref_mps',0,'eta_actual',1,...
 'eta_ref',1,'phase_rad',0,'soc',1,'battery_charge_Ah',c.battery_capacity_Ah,...
 'energy_electrical_J',0,'energy_electrical_Wh',0,'last_command',struct(),...
 'cutoff',false);
f=fieldnames(initial);for k=1:numel(f),if ~isfield(s,f{k}),error('plane:Reset','Unknown field %s',f{k});end;s.(f{k})=initial.(f{k});end
if isfield(initial,'soc')&&isfield(initial,'battery_charge_Ah'),assert(abs(initial.battery_charge_Ah-c.battery_capacity_Ah*initial.soc)<1e-9,'plane:Reset','Inconsistent SOC/charge.');elseif isfield(initial,'soc'),s.battery_charge_Ah=c.battery_capacity_Ah*initial.soc;elseif isfield(initial,'battery_charge_Ah'),s.soc=initial.battery_charge_Ah/c.battery_capacity_Ah;end
 assert(isfinite(s.soc)&&s.soc>=0&&s.soc<=1,'plane:Reset','Initial SOC must lie in [0,1].');
 s.battery_charge_Ah=c.battery_capacity_Ah*s.soc;
 windSample=struct('time_s',0,'wind_truth_ne_mps',[0;0],...
  'wind_measured_ne_mps',[0;0],'wind_valid',true);
 pathCommand=struct('time_s',0,'trajectory_type','straight',...
  'circle_center_ne_m',[NaN;NaN],'circle_radius_m',NaN,...
  'path_phase_rad',0,'path_tangent_ne',[0;1],'path_normal_ne',[-1;0],...
  'path_valid',true);
 command=struct('v_ref_applied_mps',0,'eta_ref_applied',1,...
  'controller_mode','fixed');
 [s,sample]=plane.step(s,windSample,pathCommand,command,0,c);
end
