function run_acceptance()
error('harness:NotImplemented', ...
    ['System-level acceptance is not implemented yet. Complete M0-A power, ' ...
     'constraints, and baseline configuration before adding harness scenarios.']);
end
