function c = config(varargin)
%X8PHYS.CONFIG Configuration for the uncalibrated X8 physical proxy.
% Coordinates follow air.slx/shared6dof: inertial NED and body FRD.
c = struct( ...
    'schema_version', '0.3', ...
    'parameter_source', 'proxy_static_test_fit_2026-07-04', ...
    'mass_kg', 1.4, ...
    'gravity_mps2', 9.81, ...
    'arm_m', 0.2, ...
    'rotor_radius_m', 0.508, ...
    ... % PAW 40x13.1R static test: T=0.08643*n^2, n=rev/s.
    'ct_N_per_rad2', 0.08643/(2*pi)^2, ...
    'cm_Nm_per_rad2', 1.0188e-4, ...
    'pwm_min_us', 1000, ...
    'pwm_max_us', 2000, ...
    ... % Static-test envelope ends near 1140 rpm; higher commands are clipped.
    'omega_max_radps', 2*pi/60 * 1140, ...
    'motor_kv_rpm_per_V', 76.64, ...
    'motor_tau_s', 0.08, ...
    'rotor_angle_rad', [pi/4; 7*pi/4; 5*pi/4; 3*pi/4; pi/4; 7*pi/4; 5*pi/4; 3*pi/4], ...
    'rotor_direction', [-1; 1; -1; 1; 1; -1; 1; -1], ...
    'inertia_kgm2', diag([0.025 0.025 0.045]), ...
    'drag_area_m2', [0.12; 0.12; 0.20], ...
    'air_density_kgpm3', 1.225, ...
    'drag_coefficient', [1.0; 1.0; 1.1], ...
    'rotor_advance_power_gain', 3.0, ...
    'rotor_axial_power_gain', 0.5, ...
    'cell_capacity_Ah', 24.0, ...
    'battery_series', 7, ...
    'battery_parallel', 1, ...
    'battery_capacity_Ah', 24.0, ...
    'battery_full_V', 29.4, ...
    'battery_empty_V', 19.6, ...
    'battery_cutoff_V', 19.0, ...
    'battery_resistance_ohm', 0.035, ...
    'cell_resistance_ohm', 0.005, ...
    'reserve_soc', 0.20, ...
    'battery_ocv_soc', [0; 0.17; 0.37; 0.58; 0.79; 1.0], ...
    'battery_ocv_cell_V', [2.30; 2.90; 3.30; 3.58; 3.82; 4.20], ...
    'motor_electrical_efficiency', 0.83, ...
    'esc_efficiency', 0.95, ...
    'aux_power_W', 12.0, ...
    'prop_power_linear_W_per_rev_s', 0.34467, ...
    'prop_power_cubic_W_per_rev_s3', 0.0289367, ...
    'max_soc', 1.0, ...
    'min_soc', 0.0, ...
    'max_attitude_rad', 0.523, ...
    'max_yaw_rate_radps', 1.5, ...
    'speed_tolerance_mps', 1.0, ...
    ... % Eight-motor proxy envelope; replace with confirmed pack/ESC limit.
    'max_power_W', 6000, ...
    'pwm_edge_us', 5.0);

if mod(numel(varargin), 2) ~= 0
    error('x8phys:Config', 'Use name/value pairs.');
end
for k = 1:2:numel(varargin)
    name = char(varargin{k});
    if ~isfield(c, name)
        error('x8phys:Config', 'Unknown parameter: %s', name);
    end
    c.(name) = varargin{k + 1};
end

validateattributes(c.mass_kg, {'numeric'}, {'scalar','positive','finite'});
validateattributes(c.gravity_mps2, {'numeric'}, {'scalar','positive','finite'});
validateattributes(c.arm_m, {'numeric'}, {'scalar','positive','finite'});
validateattributes(c.rotor_radius_m, {'numeric'}, {'scalar','positive','finite'});
validateattributes(c.ct_N_per_rad2, {'numeric'}, {'scalar','positive','finite'});
validateattributes(c.cm_Nm_per_rad2, {'numeric'}, {'scalar','positive','finite'});
validateattributes(c.inertia_kgm2, {'numeric'}, {'size',[3 3],'finite'});
assert(max(abs(c.inertia_kgm2-c.inertia_kgm2'),[],'all') < 1e-12, ...
    'x8phys:Config', 'Inertia must be symmetric.');
assert(all(eig((c.inertia_kgm2 + c.inertia_kgm2') / 2) > 0), ...
    'x8phys:Config', 'Inertia must be positive definite.');
assert(isfinite(c.pwm_min_us) && isfinite(c.pwm_max_us) && ...
    c.pwm_min_us < c.pwm_max_us && isfinite(c.omega_max_radps) && ...
    c.omega_max_radps > 0 && isfinite(c.motor_kv_rpm_per_V) && ...
    c.motor_kv_rpm_per_V > 0 && isfinite(c.motor_tau_s) && c.motor_tau_s > 0, ...
    'x8phys:Config', 'Invalid actuator limits.');
assert(numel(c.rotor_angle_rad) == 8 && numel(c.rotor_direction) == 8, ...
    'x8phys:Config', 'Eight rotor angles and directions are required.');
assert(all(isfinite(c.rotor_angle_rad)) && ...
    all(ismember(c.rotor_direction,[-1 1])), ...
    'x8phys:Config', 'Rotor geometry or directions are invalid.');
assert(c.battery_capacity_Ah > 0 && c.battery_cutoff_V <= c.battery_empty_V && ...
    c.battery_empty_V < c.battery_full_V, 'x8phys:Config', ...
    'Invalid battery parameters.');
assert(c.min_soc >= 0 && c.max_soc <= 1 && c.min_soc < c.max_soc, ...
    'x8phys:Config', 'SOC bounds must lie in [0,1].');
assert(c.motor_electrical_efficiency > 0 && c.motor_electrical_efficiency <= 1 && ...
    c.esc_efficiency > 0 && c.esc_efficiency <= 1, ...
    'x8phys:Config', 'Efficiencies must lie in (0,1].');
assert(c.battery_series >= 1 && c.battery_parallel >= 1 && ...
    fix(c.battery_series) == c.battery_series && ...
    fix(c.battery_parallel) == c.battery_parallel && ...
    c.cell_capacity_Ah > 0 && c.battery_capacity_Ah == c.cell_capacity_Ah * c.battery_parallel, ...
    'x8phys:Config', 'Battery series/parallel capacity is inconsistent.');
assert(c.cell_resistance_ohm > 0 && c.battery_resistance_ohm > 0 && ...
    abs(c.battery_resistance_ohm - c.cell_resistance_ohm * c.battery_series / c.battery_parallel) < 1e-12, ...
    'x8phys:Config', 'Battery resistance is inconsistent with cell parameters.');
assert(numel(c.battery_ocv_soc) == numel(c.battery_ocv_cell_V) && ...
    all(diff(c.battery_ocv_soc) > 0) && all(diff(c.battery_ocv_cell_V) > 0), ...
    'x8phys:Config', 'OCV lookup table must be strictly increasing.');
assert(c.battery_ocv_soc(1) <= c.min_soc && ...
    c.battery_ocv_soc(end) >= c.max_soc && ...
    c.battery_cutoff_V >= c.battery_series*c.battery_ocv_cell_V(1) && ...
    c.battery_full_V <= c.battery_series*c.battery_ocv_cell_V(end), ...
    'x8phys:Config', 'OCV table does not cover the configured battery window.');
assert(c.reserve_soc >= c.min_soc && c.reserve_soc <= c.max_soc, ...
    'x8phys:Config', 'Reserve SOC must lie within configured bounds.');
assert(all(isfinite(c.drag_area_m2)) && all(c.drag_area_m2 >= 0) && ...
    all(isfinite(c.drag_coefficient)) && all(c.drag_coefficient >= 0) && ...
    c.rotor_advance_power_gain >= 0 && c.rotor_axial_power_gain >= 0 && ...
    c.prop_power_linear_W_per_rev_s >= 0 && ...
    c.prop_power_cubic_W_per_rev_s3 > 0 && c.aux_power_W >= 0 && ...
    c.max_power_W > 0 && c.pwm_edge_us >= 0 && ...
    c.pwm_edge_us < (c.pwm_max_us-c.pwm_min_us)/2, ...
    'x8phys:Config', 'Invalid load, power, or diagnostic parameters.');
end
