function [s, sample, truth] = platform_step(s, platform, windNed, dt, c)
%X8PHYS.PLATFORM_STEP Bridge PX4 outputs to the M0 measurement contract.
% Required platform field: motor_pwm_us. Optional v_ref_mps is used only
% for flag 5; it never enters the physical dynamics.
if nargin < 5 || isempty(c), c=x8phys.config(); end
assert(isstruct(platform) && isfield(platform,'motor_pwm_us'), ...
    'x8phys:Platform', 'platform.motor_pwm_us is required.');
if nargin < 3 || isempty(windNed)
    if isfield(platform,'wind_ned_mps')
        windNed=platform.wind_ned_mps;
    else
        windNed=zeros(3,1);
    end
end
validateattributes(dt,{'numeric'},{'scalar','finite','nonnegative'});
cmd=struct('pwm_us',platform.motor_pwm_us,'wind_ned_mps',windNed);
[s,truth]=x8phys.step(s,cmd,dt,c);
flagPlatform=platform;
if ~isfield(flagPlatform,'attitude_tol_rad'),flagPlatform.attitude_tol_rad=c.max_attitude_rad;end
if ~isfield(flagPlatform,'yaw_rate_tol_radps'),flagPlatform.yaw_rate_tol_radps=c.max_yaw_rate_radps;end
if ~isfield(flagPlatform,'speed_tol_mps'),flagPlatform.speed_tol_mps=c.speed_tolerance_mps;end
if ~isfield(flagPlatform,'max_power_W'),flagPlatform.max_power_W=c.max_power_W;end
validateattributes([flagPlatform.attitude_tol_rad,flagPlatform.yaw_rate_tol_radps, ...
    flagPlatform.speed_tol_mps,flagPlatform.max_power_W],{'numeric'}, ...
    {'vector','numel',4,'positive','finite'});
flags=x8phys.map_flags(truth,flagPlatform);
sample=struct( ...
    't',truth.time_s, ...
    'v',norm(truth.velocity_ned_mps(1:2)), ...
    'P_e',truth.electrical_power_W, ...
    'E_e',truth.energy_electrical_J, ...
    'attitude',[truth.attitude_rad;truth.body_rate_radps], ...
    'yaw_rate',truth.body_rate_radps(3), ...
    'motor_pwm',truth.pwm_applied_us, ...
    'motor_rpm',truth.rotor_omega_radps*60/(2*pi), ...
    'constraint_flags',flags, ...
    'power_source',0, ...
    'voltage_v',truth.battery_voltage_V, ...
    'current_a',truth.battery_current_A, ...
    'soc',truth.soc, ...
    'valid',false);
finiteMeasurement = all(isfinite([sample.t;sample.v;sample.P_e;sample.E_e; ...
    sample.attitude;sample.yaw_rate;sample.motor_pwm;sample.motor_rpm; ...
    sample.voltage_v;sample.current_a;sample.soc]));
sample.valid = finiteMeasurement && all(flags([1 2 3 4 6 7]) == 0);
end
