function [s, out] = reset(c, initial)
%X8PHYS.RESET Initialize a self-consistent motion and battery state.
if nargin < 1 || isempty(c), c = x8phys.config(); end
if nargin < 2, initial = struct(); end

s = struct( ...
    'time_s', 0, ...
    'position_ned_m', zeros(3,1), ...
    'velocity_ned_mps', zeros(3,1), ...
    'quaternion_bn', [1;0;0;0], ...
    'body_rate_radps', zeros(3,1), ...
    'soc', c.max_soc, ...
    'battery_charge_Ah', c.battery_capacity_Ah * c.max_soc, ...
    'energy_electrical_J', 0, ...
    'energy_shaft_J', 0, ...
    'last_pwm_us', ones(8,1) * c.pwm_min_us, ...
    'battery_cutoff', false);

% Rotor state is explicit so PWM commands have a finite execution dynamic.
s.rotor_omega_radps = zeros(8,1);

allowed = [fieldnames(s); {'attitude_rad'}];
names = fieldnames(initial);
for k = 1:numel(names)
    if ~ismember(names{k}, allowed)
        error('x8phys:Reset', 'Unknown initial field %s.', names{k});
    end
end
assert(~(isfield(initial,'attitude_rad') && isfield(initial,'quaternion_bn')), ...
    'x8phys:Reset', 'Specify attitude_rad or quaternion_bn, not both.');

hasSoc = isfield(initial, 'soc');
hasCharge = isfield(initial, 'battery_charge_Ah');
if hasSoc && hasCharge
    expected = c.battery_capacity_Ah * initial.soc;
    assert(abs(initial.battery_charge_Ah - expected) < 1e-9, ...
        'x8phys:Reset', 'Initial SOC and charge are inconsistent.');
elseif hasSoc
    initial.battery_charge_Ah = c.battery_capacity_Ah * initial.soc;
elseif hasCharge
    initial.soc = initial.battery_charge_Ah / c.battery_capacity_Ah;
end

names = fieldnames(initial);
for k = 1:numel(names)
    if ~strcmp(names{k}, 'attitude_rad')
        s.(names{k}) = initial.(names{k});
    end
end
s.soc = double(s.soc);
assert(isfinite(s.soc) && s.soc >= c.min_soc && s.soc <= c.max_soc, ...
    'x8phys:Reset', 'Initial SOC is outside configured bounds.');
if isfield(initial, 'attitude_rad')
    s.quaternion_bn = x8phys.euler_to_quaternion(initial.attitude_rad);
end
s.battery_charge_Ah = c.battery_capacity_Ah * s.soc;
s.quaternion_bn = double(s.quaternion_bn(:));
assert(numel(s.quaternion_bn) == 4 && all(isfinite(s.quaternion_bn)) && ...
    norm(s.quaternion_bn) > eps, 'x8phys:Reset', ...
    'Initial quaternion must be a finite, nonzero 4-vector.');
s.quaternion_bn = s.quaternion_bn / norm(s.quaternion_bn);
s.battery_cutoff = logical(s.battery_cutoff) || s.soc <= c.min_soc;

assert(isequal(size(s.rotor_omega_radps), [8 1]) && all(isfinite(s.rotor_omega_radps)), ...
    'x8phys:Reset', 'Initial rotor speed state is invalid.');
assert(all(s.rotor_omega_radps >= 0) && all(s.rotor_omega_radps <= c.omega_max_radps), ...
    'x8phys:Reset', 'Initial rotor speed is outside configured bounds.');
assert(isequal(size(s.position_ned_m),[3 1]) && all(isfinite(s.position_ned_m)) && ...
    isequal(size(s.velocity_ned_mps),[3 1]) && all(isfinite(s.velocity_ned_mps)) && ...
    isequal(size(s.body_rate_radps),[3 1]) && all(isfinite(s.body_rate_radps)), ...
    'x8phys:Reset', 'Initial motion state must contain finite 3-vectors.');
assert(isfinite(s.time_s) && s.time_s >= 0 && ...
    isfinite(s.energy_electrical_J) && s.energy_electrical_J >= 0 && ...
    isfinite(s.energy_shaft_J) && s.energy_shaft_J >= 0, ...
    'x8phys:Reset', 'Initial time and energies must be finite and nonnegative.');
assert(numel(s.last_pwm_us) == 8 && all(isfinite(s.last_pwm_us)) && ...
    all(s.last_pwm_us >= c.pwm_min_us) && all(s.last_pwm_us <= c.pwm_max_us), ...
    'x8phys:Reset', 'Initial applied PWM is outside configured bounds.');

[s, out] = x8phys.step(s, struct('pwm_us',s.last_pwm_us, ...
    'wind_ned_mps',zeros(3,1)), 0, c);
end
