function [s, out] = step(s, cmd, dt, c)
%X8PHYS.STEP Advance NED motion, wind load and battery state.
if nargin < 4 || isempty(c), c = x8phys.config(); end
validateattributes(dt, {'numeric'}, {'scalar','nonnegative','finite'});
assert(isfield(cmd, 'pwm_us'), 'x8phys:Input', 'cmd.pwm_us is required.');
pwmRequested = double(cmd.pwm_us(:));
assert(numel(pwmRequested) == 8 && all(isfinite(pwmRequested)), ...
    'x8phys:Input', 'pwm_us must be 8 finite values.');
if isfield(cmd, 'wind_ned_mps')
    wind = double(cmd.wind_ned_mps(:));
else
    wind = zeros(3,1);
end
assert(numel(wind) == 3 && all(isfinite(wind)), ...
    'x8phys:Input', 'wind_ned_mps must be a finite 3-vector.');

pwmLimited = min(max(pwmRequested, c.pwm_min_us), c.pwm_max_us);
cutoffAtStart = logical(s.battery_cutoff);
if cutoffAtStart
    pwmApplied = ones(8,1) * c.pwm_min_us;
else
    pwmApplied = pwmLimited;
end
throttle = (pwmApplied - c.pwm_min_us) / (c.pwm_max_us - c.pwm_min_us);
throttle = min(1, max(0, throttle));
Rbn = x8phys.quaternion_rotation(s.quaternion_bn);
velocity0 = s.velocity_ned_mps;
relativeAir0 = velocity0 - wind;
relativeAirBody0 = Rbn' * relativeAir0;

openVoltage = battery_ocv(s.soc, c);
voltageGuess = openVoltage;
omega0 = s.rotor_omega_radps(:);
omega = omega0;
% Fixed-point coupling: battery voltage affects RPM, RPM affects power/current.
for k = 1:4
    omegaTarget = throttle .* (c.motor_kv_rpm_per_V * voltageGuess * 2*pi/60);
    if dt > 0
        alpha = 1 - exp(-dt / c.motor_tau_s);
        omega = omega0 + alpha .* (omegaTarget - omega0);
    else
        omega = omega0;
    end
    omega = min(c.omega_max_radps, max(0, omega));
    nRevPerS = omega / (2*pi);
    tipSpeed = max(omega * c.rotor_radius_m, 1);
    diskSpeed = hypot(relativeAirBody0(1), relativeAirBody0(2));
    advanceRatio = diskSpeed ./ tipSpeed;
    axialRatio = abs(relativeAirBody0(3)) ./ tipSpeed;
    loadFactor = 1 + c.rotor_advance_power_gain * advanceRatio.^2 + ...
        c.rotor_axial_power_gain * axialRatio;
    shaftPowerBaseline = sum(c.cm_Nm_per_rad2 * omega.^3);
    shaftPower = sum(c.cm_Nm_per_rad2 * omega.^3 .* loadFactor);
    electricalPowerDemand = sum(c.prop_power_linear_W_per_rev_s .* nRevPerS + ...
        c.prop_power_cubic_W_per_rev_s3 .* nRevPerS.^3 .* loadFactor) + c.aux_power_W;
    maxBatteryPower = openVoltage^2 / (4*c.battery_resistance_ohm);
    electricalPower = min(electricalPowerDemand,maxBatteryPower);
    discriminant = max(0, openVoltage^2 - 4*c.battery_resistance_ohm*electricalPower);
    current = 2 * electricalPower / max(openVoltage + sqrt(discriminant), eps);
    voltageGuess = max(0, openVoltage - c.battery_resistance_ohm * current);
end

thrust = c.ct_N_per_rad2 * omega.^2;
torque = c.cm_Nm_per_rad2 * omega.^2;
angle = c.rotor_angle_rad(:);
direction = c.rotor_direction(:);
% Exact motor geometry/sign convention extracted from air.slx chart_14.
forceBody = [0; 0; -sum(thrust)];
momentBody = [sum(-c.arm_m * sin(angle) .* thrust); ...
              sum( c.arm_m * cos(angle) .* thrust); ...
              sum(-direction .* torque)];
dragBody = -0.5 * c.air_density_kgpm3 .* c.drag_coefficient(:) .* ...
    c.drag_area_m2(:) .* relativeAirBody0 .* abs(relativeAirBody0);
forceNed = Rbn * (forceBody + dragBody) + ...
    [0; 0; c.mass_kg * c.gravity_mps2];
acceleration = forceNed / c.mass_kg;

bodyRate0 = s.body_rate_radps;
angularAcceleration = c.inertia_kgm2 \ ...
    (momentBody - cross(bodyRate0, c.inertia_kgm2 * bodyRate0));
if dt > 0
    s.position_ned_m = s.position_ned_m + velocity0 * dt + ...
        0.5 * acceleration * dt^2;
    s.velocity_ned_mps = velocity0 + acceleration * dt;
    s.body_rate_radps = bodyRate0 + angularAcceleration * dt;
    midpointRate = 0.5 * (bodyRate0 + s.body_rate_radps);
    s.quaternion_bn = x8phys.quaternion_advance( ...
        s.quaternion_bn, midpointRate, dt);
    s.time_s = s.time_s + dt;
end

powerLimited = electricalPowerDemand > maxBatteryPower;
if cutoffAtStart
    electricalPower = 0;
    electricalPowerDemand = 0;
    current = 0;
    voltage = openVoltage;
else
    discriminant = max(0,openVoltage^2 - ...
        4 * c.battery_resistance_ohm * electricalPower);
    current = 2 * electricalPower / (openVoltage + sqrt(discriminant));
    voltage = max(0, openVoltage - c.battery_resistance_ohm * current);
    if dt > 0
        s.battery_charge_Ah = max(0, s.battery_charge_Ah - current * dt / 3600);
        s.soc = min(c.max_soc, max(c.min_soc, ...
            s.battery_charge_Ah / c.battery_capacity_Ah));
    end
    if dt > 0 && (voltage <= c.battery_cutoff_V || s.soc <= c.min_soc)
        s.battery_cutoff = true;
    end
end

energyStep = electricalPower * dt;
shaftEnergyStep = shaftPower * dt;
s.energy_electrical_J = s.energy_electrical_J + energyStep;
s.energy_shaft_J = s.energy_shaft_J + shaftEnergyStep;
if dt > 0
    s.last_pwm_us = pwmApplied;
    s.rotor_omega_radps = omega;
end

objectFlags = struct( ...
    'pwm_clipped', any(pwmRequested ~= pwmLimited), ...
    'pwm_at_edge', any(pwmApplied <= c.pwm_min_us + c.pwm_edge_us | ...
                       pwmApplied >= c.pwm_max_us - c.pwm_edge_us), ...
    'rpm_at_edge', any(omega <= c.pwm_edge_us * c.omega_max_radps / ...
                       (c.pwm_max_us-c.pwm_min_us) | ...
                       omega >= c.omega_max_radps * (1-c.pwm_edge_us / ...
                       (c.pwm_max_us-c.pwm_min_us))), ...
    'power_limited', powerLimited, ...
    'low_voltage', voltage <= c.battery_empty_V, ...
    'battery_cutoff', logical(s.battery_cutoff));

attitude = x8phys.quaternion_to_euler(s.quaternion_bn);
out = struct( ...
    'time_s', s.time_s, ...
    'position_ned_m', s.position_ned_m, ...
    'velocity_ned_mps', s.velocity_ned_mps, ...
    'quaternion_bn', s.quaternion_bn, ...
    'attitude_rad', attitude, ...
    'body_rate_radps', s.body_rate_radps, ...
    'wind_ned_mps', wind, ...
    'relative_air_velocity_mps', s.velocity_ned_mps - wind, ...
    'relative_air_velocity_force_mps', relativeAir0, ...
    'pwm_requested_us', pwmRequested, ...
    'pwm_applied_us', pwmApplied, ...
    'rotor_omega_radps', omega, ...
    'rotor_thrust_N', thrust, ...
    'force_inertial_N', forceNed, ...
    'moment_body_Nm', momentBody, ...
    'acceleration_mps2', acceleration, ...
    'shaft_power_baseline_W', shaftPowerBaseline, ...
    'shaft_power_W', shaftPower, ...
    'electrical_power_demand_W', electricalPowerDemand, ...
    'electrical_power_W', electricalPower, ...
    'battery_voltage_V', voltage, ...
    'battery_current_A', current, ...
    'soc', s.soc, ...
    'energy_step_J', energyStep, ...
    'energy_electrical_J', s.energy_electrical_J, ...
    'energy_electrical_Wh', s.energy_electrical_J / 3600, ...
    'energy_shaft_J', s.energy_shaft_J, ...
    'object_flags', objectFlags, ...
    'constraint_flags', x8phys.map_flags(struct('object_flags',objectFlags, ...
        'attitude_rad',attitude,'body_rate_radps',s.body_rate_radps, ...
        'velocity_ned_mps',s.velocity_ned_mps,'electrical_power_W',electricalPower, ...
        'soc',s.soc)), ...
    'power_source', 0);
end

function voltage = battery_ocv(soc, c)
% Battery report OCV points are per cell; scale by configured series count.
cellV = interp1(c.battery_ocv_soc, c.battery_ocv_cell_V, ...
    min(c.max_soc, max(c.min_soc, double(soc))), 'linear', 'extrap');
voltage = c.battery_series * cellV;
end
