function result = add_air_m0b_speed_loop()
%ADD_AIR_M0B_SPEED_LOOP Install the M0-B speed outer loop on air_spare.slx.
%   Single atomic modification of the development model only; air.slx stays
%   untouched. Requires the M0-A observation layer to be present.
%
%   Architecture (roadmap PROJECT_EXECUTION_ROADMAP.md section 6):
%     1. Reference selector + safety monitor ("M0B Reference & Safety")
%        - optimizer_enable = 0 -> fixed manual v_ref, status 0 (baseline)
%        - optimizer_enable = 1 -> optimizer v_ref with warm-up ramp, status 1/2
%        - any hard constraint flag (1,2,3,4,6,7) -> frozen (status 3, hold
%          last reference) then fallback to manual (status 4); flag 5
%          (speed miss) is logged but does not gate the optimizer.
%        - range limit [0,15] m/s, rate limit 2 m/s per s
%     2. Speed controller ("M0B Speed Controller")
%        - v_ref -> PI -> normalized pitch_cmd in the chart_23 domain
%          (theta_des = 0.523 * pitch_cmd); projection-aware sign so that
%          deceleration always opposes the current Ve_x direction.
%        - clamps: |pitch_cmd| <= 0.40 (theta_des <= 0.209 rad), integral
%          0.15, rate 0.25 /s; fully reset when the loop is disabled.
%     3. Pitch insertion inside "Attitude Control" (two new wrapper inputs)
%        - Demux of InputConditioning out 2 (Roll_Pitch) -> Switch on
%          speed_loop_enable -> Mux -> AttitudeControl input 3.
%        - speed_loop_enable = 0 passes the original pitch element unchanged
%          (bit-exact baseline); = 1 routes the M0-B command. roll, yaw,
%          thrust and arming paths are not touched.
%     4. Flag 5 semantics upgrade inside "M0A Constraint Flags"
%        - speed miss becomes |v - v_ref| > tol with the live rate-limited
%          v_ref passed through a one-step unit delay (avoids the algebraic
%          loop flags -> selector -> flags).
%     5. New observability: Subsystem outport 9 = Ve_x; ZOH to 1 ms.
%     6. m0b_log_bus (7, 1 ms):
%        [v_ref, pitch_cmd, v_err, optimizer_status, speed_loop_enable,
%         ve_x, v]
%
%   Defaults saved with the model: speed_loop_enable = 0, optimizer_enable
%   = 0, v_ref_manual = 5, v_ref_optimizer = 5 -> identical behaviour to the
%   M0-A snapshot until the test scripts enable the loop in memory.

model = 'air_spare';
modelDir = fileparts(mfilename('fullpath'));
wsRoot = fileparts(fileparts(modelDir));
wasLoaded = bdIsLoaded(model);
if ~wasLoaded
    load_system(fullfile(modelDir, [model '.slx']));
end
dirtyBefore = get_param(model, 'Dirty');

try
    set_param(model, 'SimulationCommand', 'update');

    acWrapper = [model '/Attitude Control'];
    acInner = [acWrapper '/AttitudeControl'];
    subSystem = [model '/Subsystem'];
    flagsBlock = [model '/M0A Constraint Flags'];
    flagsCore = [flagsBlock '/M0A Flags Core'];
    enableConst = [model '/M0A Optimizer Enable'];

    selBlock = [model '/M0B Reference & Safety'];
    ctrlBlock = [model '/M0B Speed Controller'];
    vRefManual = [model '/M0B v Ref Manual'];
    vRefOpt = [model '/M0B v Ref Optimizer'];
    loopEnable = [model '/M0B Speed Loop Enable'];
    tsConst = [model '/M0B Ts'];
    vZoh = [model '/M0B v ZOH 1ms'];
    vexZoh = [model '/M0B Ve X ZOH 1ms'];
    refDelay = [model '/M0B v Ref Unit Delay'];
    attTolConst = [model '/M0B Att Tol'];
    busMux = [model '/M0B Log Bus'];
    logBus = [model '/M0B Log Log Bus'];
    vexFcn = [subSystem '/M0B Ve X'];
    vexOut = [subSystem '/M0B Ve X Obs Out'];
    pitchIn = [acWrapper '/m0b_pitch_cmd'];
    loopIn = [acWrapper '/m0b_speed_loop_enable'];
    pitchDemux = [acWrapper '/M0B Pitch Demux'];
    pitchMux = [acWrapper '/M0B Pitch Mux'];
    pitchDtc = [acWrapper '/M0B Pitch DTC'];
    blendSum = [acWrapper '/M0B Pitch Blend'];
    blendOrig = [acWrapper '/M0B Orig Blend'];
    blendM0b = [acWrapper '/M0B M0B Blend'];
    enableNeg = [acWrapper '/M0B Enable Neg'];
    oneConst = [acWrapper '/M0B One Const'];
    oneMinusE = [acWrapper '/M0B One Minus Enable'];

    targets = {selBlock, ctrlBlock, vRefManual, vRefOpt, loopEnable, tsConst, ...
        vZoh, vexZoh, refDelay, attTolConst, busMux, logBus, vexFcn, vexOut, ...
        pitchIn, loopIn, pitchDemux, pitchMux, pitchDtc, blendSum, ...
        blendOrig, blendM0b, enableNeg, oneConst, oneMinusE, ...
        [model '/M0B Flags Override'], [model '/M0B Speed Tol']};
    assert(~any(cellfun(@isBlock, targets)), ...
        'air:M0B:AlreadyInstalled', ...
        'M0-B speed loop blocks already exist. No changes were made.');
    assert(isBlock(enableConst) && isBlock(flagsBlock), ...
        'air:M0B:M0ALayerMissing', 'Run the M0-A install scripts first.');

    % ---------- 1. Ve_x observation outlet inside Subsystem ----------
    hSpeed = [subSystem '/M0A Horizontal Speed'];
    assert(isBlock(hSpeed), 'air:M0B:SpeedBlockMissing', ...
        'M0A Horizontal Speed not found.');
    hsLine = get_param(get_param(hSpeed, 'PortHandles').Inport(1), 'Line');
    assert(hsLine ~= -1, 'air:M0B:SpeedLineMissing', ...
        'M0A Horizontal Speed input line not found.');
    veSrc = get_param(hsLine, 'SrcPortHandle');
    hsPos = get_param(hSpeed, 'Position');
    add_block('simulink/User-Defined Functions/Fcn', vexFcn, ...
        'Position', [hsPos(1), hsPos(2) + 120, hsPos(1) + 130, hsPos(2) + 155], ...
        'Expr', 'u(1)');
    add_line(subSystem, veSrc, ...
        get_param(vexFcn, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_block('built-in/Outport', vexOut, ...
        'Position', [hsPos(3) + 160, hsPos(2) + 150, hsPos(3) + 190, hsPos(2) + 164], ...
        'Port', '9');
    add_line(subSystem, get_param(vexFcn, 'PortHandles').Outport(1), ...
        get_param(vexOut, 'PortHandles').Inport(1), 'autorouting', 'on');

    % ---------- 2. root constants and rate alignment ----------
    demuxPosition = get_param([model '/Demux'], 'Position');
    x0 = demuxPosition(3) + 200;
    y1 = demuxPosition(4) + 950;

    add_block('simulink/Discrete/Zero-Order Hold', vZoh, ...
        'Position', [x0, y1, x0 + 40, y1 + 30], 'SampleTime', '0.001');
    add_block('simulink/Discrete/Zero-Order Hold', vexZoh, ...
        'Position', [x0, y1 + 60, x0 + 40, y1 + 90], 'SampleTime', '0.001');
    add_line(model, get_param(subSystem, 'PortHandles').Outport(8), ...
        get_param(vZoh, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, get_param(subSystem, 'PortHandles').Outport(9), ...
        get_param(vexZoh, 'PortHandles').Inport(1), 'autorouting', 'on');

    add_block('simulink/Sources/Constant', vRefManual, ...
        'Position', [x0 + 120, y1 - 60, x0 + 150, y1 - 30], 'Value', '5');
    add_block('simulink/Sources/Constant', vRefOpt, ...
        'Position', [x0 + 220, y1 - 60, x0 + 250, y1 - 30], 'Value', '5');
    add_block('simulink/Sources/Constant', loopEnable, ...
        'Position', [x0 + 320, y1 - 60, x0 + 350, y1 - 30], 'Value', '0');
    add_block('simulink/Sources/Constant', tsConst, ...
        'Position', [x0 + 420, y1 - 60, x0 + 450, y1 - 30], 'Value', '0.001');
    add_block('simulink/Sources/Constant', attTolConst, ...
        'Position', [x0 + 500, y1 - 60, x0 + 530, y1 - 30], 'Value', '0.523');

    % ---------- 3. reference selector + safety monitor ----------
    add_block('built-in/Subsystem', selBlock, ...
        'Position', [x0 + 120, y1 + 120, x0 + 320, y1 + 300]);
    selIn = {'optimizer_enable', 'v_ref_manual', 'v_ref_optimizer', 'flags', 'Ts'};
    for k = 1:numel(selIn)
        add_block('built-in/Inport', [selBlock '/' selIn{k}], ...
            'Position', [30, 33 + 30 * (k - 1), 60, 47 + 30 * (k - 1)], ...
            'Port', num2str(k));
    end
    add_block('built-in/Outport', [selBlock '/v_ref'], ...
        'Position', [380, 63, 410, 77], 'Port', '1');
    add_block('built-in/Outport', [selBlock '/status'], ...
        'Position', [380, 108, 410, 122], 'Port', '2');
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [selBlock '/M0B Ref Safety Core'], 'Position', [140, 70, 310, 140]);
    rt = sfroot;
    schart = find(rt, '-isa', 'Stateflow.EMChart', ...
        'Path', [selBlock '/M0B Ref Safety Core']);
    assert(numel(schart) == 1, 'air:M0B:ChartNotFound', 'selector chart missing');
    schart.Script = [ ...
        'function [v_ref, status] = fcn(optimizer_enable, v_ref_manual, v_ref_optimizer, flags, Ts)' newline ...
        '% M0-B reference selector + safety monitor. Safety lives here,' newline ...
        '% never inside the future ESC core.' newline ...
        '% status: 0 fixed baseline | 1 warm-up ramp | 2 active' newline ...
        '%         3 frozen (hold last ref) | 4 fallback (manual ref)' newline ...
        'persistent ref_prev hold_t clear_t fallback_latch;' newline ...
        'if isempty(ref_prev)' newline ...
        '    ref_prev = 0.0; hold_t = 0.0; clear_t = 0.0; fallback_latch = false;' newline ...
        'end' newline ...
        'v_min = 0.0; v_max = 15.0;   % v_ref range limit, m/s' newline ...
        'rate_max = 2.0;              % v_ref rate limit, m/s per s' newline ...
        'hold_max = 0.5;              % s frozen before fallback' newline ...
        'clear_max = 1.5;             % s flag-free before re-engage' newline ...
        'hard = any(flags([1 2 3 4 6 7]) > 0.5); % flag 5 logged, not gating' newline ...
        'if optimizer_enable < 0.5' newline ...
        '    target = v_ref_manual; status = 0.0;' newline ...
        '    hold_t = 0.0; clear_t = 0.0; fallback_latch = false;' newline ...
        'elseif hard' newline ...
        '    clear_t = 0.0;' newline ...
        '    if fallback_latch || hold_t >= hold_max' newline ...
        '        fallback_latch = true;' newline ...
        '        target = v_ref_manual; status = 4.0;' newline ...
        '    else' newline ...
        '        hold_t = hold_t + Ts;' newline ...
        '        target = ref_prev; status = 3.0;' newline ...
        '    end' newline ...
        'else' newline ...
        '    hold_t = 0.0;' newline ...
        '    if fallback_latch' newline ...
        '        clear_t = clear_t + Ts;' newline ...
        '        if clear_t >= clear_max' newline ...
        '            fallback_latch = false;' newline ...
        '        end' newline ...
        '        target = v_ref_manual; status = 4.0;' newline ...
        '    else' newline ...
        '        target = v_ref_optimizer; status = 2.0;' newline ...
        '    end' newline ...
        'end' newline ...
        'target = min(v_max, max(v_min, target));' newline ...
        'step_max = rate_max * Ts;' newline ...
        'ramped = min(target, ref_prev + step_max);' newline ...
        'ramped = max(ramped, ref_prev - step_max);' newline ...
        'if status == 2.0 && abs(ramped - target) > 1e-9' newline ...
        '    status = 1.0; % still ramping toward the selected reference' newline ...
        'end' newline ...
        'ref_prev = ramped;' newline ...
        'v_ref = ramped;' newline ...
        'end'];
    % persistent-variable chart must not inherit a continuous sample time
    % (constants drive some inputs); pin it to the 1 ms solver grid
    set_param([selBlock '/M0B Ref Safety Core'], 'SystemSampleTime', '0.001');
    for k = 1:numel(selIn)
        add_line(selBlock, ...
            get_param([selBlock '/' selIn{k}], 'PortHandles').Outport(1), ...
            get_param([selBlock '/M0B Ref Safety Core'], 'PortHandles').Inport(k), ...
            'autorouting', 'on');
    end
    add_line(selBlock, ...
        get_param([selBlock '/M0B Ref Safety Core'], 'PortHandles').Outport(1), ...
        get_param([selBlock '/v_ref'], 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(selBlock, ...
        get_param([selBlock '/M0B Ref Safety Core'], 'PortHandles').Outport(2), ...
        get_param([selBlock '/status'], 'PortHandles').Inport(1), 'autorouting', 'on');

    selPorts = get_param(selBlock, 'PortHandles');
    add_line(model, get_param(enableConst, 'PortHandles').Outport(1), ...
        selPorts.Inport(1), 'autorouting', 'on');
    add_line(model, get_param(vRefManual, 'PortHandles').Outport(1), ...
        selPorts.Inport(2), 'autorouting', 'on');
    add_line(model, get_param(vRefOpt, 'PortHandles').Outport(1), ...
        selPorts.Inport(3), 'autorouting', 'on');
    add_line(model, get_param(flagsBlock, 'PortHandles').Outport(1), ...
        selPorts.Inport(4), 'autorouting', 'on');
    add_line(model, get_param(tsConst, 'PortHandles').Outport(1), ...
        selPorts.Inport(5), 'autorouting', 'on');

    % ---------- 4. speed controller ----------
    add_block('built-in/Subsystem', ctrlBlock, ...
        'Position', [x0 + 380, y1 + 120, x0 + 580, y1 + 300]);
    ctlIn = {'enable', 'v', 've_x', 'v_ref', 'Ts'};
    for k = 1:numel(ctlIn)
        add_block('built-in/Inport', [ctrlBlock '/' ctlIn{k}], ...
            'Position', [30, 33 + 30 * (k - 1), 60, 47 + 30 * (k - 1)], ...
            'Port', num2str(k));
    end
    add_block('built-in/Outport', [ctrlBlock '/pitch_cmd'], ...
        'Position', [380, 63, 410, 77], 'Port', '1');
    add_block('built-in/Outport', [ctrlBlock '/v_err'], ...
        'Position', [380, 108, 410, 122], 'Port', '2');
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [ctrlBlock '/M0B Speed Core'], 'Position', [140, 70, 310, 140]);
    cchart = find(rt, '-isa', 'Stateflow.EMChart', ...
        'Path', [ctrlBlock '/M0B Speed Core']);
    assert(numel(cchart) == 1, 'air:M0B:ChartNotFound', 'controller chart missing');
    cchart.Script = [ ...
        'function [pitch_cmd, v_err] = fcn(enable, v, ve_x, v_ref, Ts)' newline ...
        '% M0-B speed outer loop: v_ref -> PI -> normalized pitch command' newline ...
        '% in the chart_23 domain (theta_des = 0.523 * pitch_cmd).' newline ...
        '% Sign convention (measured): positive pitch_cmd tilts thrust' newline ...
        '% against +Ve_x, i.e. decelerates +x flight and accelerates -x.' newline ...
        '% roll, yaw and thrust paths are untouched by design.' newline ...
        'persistent integ prev_cmd;' newline ...
        'if isempty(integ)' newline ...
        '    integ = 0.0; prev_cmd = 0.0;' newline ...
        'end' newline ...
        'Kp = 0.06;        % per m/s' newline ...
        'Ki = 0.02;        % per (m/s * s)' newline ...
        'integ_max = 0.15; % integral clamp, normalized units' newline ...
        'cmd_max = 0.40;   % |theta_des| <= 0.209 rad' newline ...
        'rate_max = 0.25;  % normalized units per s (soft engage)' newline ...
        'if enable < 0.5' newline ...
        '    integ = 0.0; prev_cmd = 0.0;' newline ...
        '    pitch_cmd = 0.0; v_err = 0.0;' newline ...
        '    return;' newline ...
        'end' newline ...
        'e = v_ref - v;                   % > 0: below reference' newline ...
        'if e < -0.10 && ve_x < 0.0' newline ...
        '    s2 = -1.0; % too fast while flying -x: oppose the -x motion' newline ...
        'else' newline ...
        '    s2 = 1.0;  % default: nose-down accelerates +x (bootstrap)' newline ...
        'end' newline ...
        'e_eff = e * s2;' newline ...
        'integ = min(integ_max, max(-integ_max, integ + e_eff * Ts));' newline ...
        'cmd_raw = -(Kp * e_eff + Ki * integ);' newline ...
        'cmd = min(cmd_max, max(-cmd_max, cmd_raw));' newline ...
        'step_max = rate_max * Ts;' newline ...
        'cmd = min(prev_cmd + step_max, max(prev_cmd - step_max, cmd));' newline ...
        'prev_cmd = cmd;' newline ...
        'pitch_cmd = cmd;' newline ...
        'v_err = e;' newline ...
        'end'];
    set_param([ctrlBlock '/M0B Speed Core'], 'SystemSampleTime', '0.001');
    for k = 1:numel(ctlIn)
        add_line(ctrlBlock, ...
            get_param([ctrlBlock '/' ctlIn{k}], 'PortHandles').Outport(1), ...
            get_param([ctrlBlock '/M0B Speed Core'], 'PortHandles').Inport(k), ...
            'autorouting', 'on');
    end
    add_line(ctrlBlock, ...
        get_param([ctrlBlock '/M0B Speed Core'], 'PortHandles').Outport(1), ...
        get_param([ctrlBlock '/pitch_cmd'], 'PortHandles').Inport(1), ...
        'autorouting', 'on');
    add_line(ctrlBlock, ...
        get_param([ctrlBlock '/M0B Speed Core'], 'PortHandles').Outport(2), ...
        get_param([ctrlBlock '/v_err'], 'PortHandles').Inport(1), ...
        'autorouting', 'on');

    ctlPorts = get_param(ctrlBlock, 'PortHandles');
    add_line(model, get_param(loopEnable, 'PortHandles').Outport(1), ...
        ctlPorts.Inport(1), 'autorouting', 'on');
    add_line(model, get_param(vZoh, 'PortHandles').Outport(1), ...
        ctlPorts.Inport(2), 'autorouting', 'on');
    add_line(model, get_param(vexZoh, 'PortHandles').Outport(1), ...
        ctlPorts.Inport(3), 'autorouting', 'on');
    add_line(model, selPorts.Outport(1), ...
        ctlPorts.Inport(4), 'autorouting', 'on');
    add_line(model, get_param(tsConst, 'PortHandles').Outport(1), ...
        ctlPorts.Inport(5), 'autorouting', 'on');

    % ---------- 5. pitch insertion inside Attitude Control ----------
    add_block('built-in/Inport', pitchIn, ...
        'Position', [30, 620, 60, 634], 'Port', '13');
    add_block('built-in/Inport', loopIn, ...
        'Position', [30, 670, 60, 684], 'Port', '14');
    icPorts = get_param([acWrapper '/InputConditioning'], 'PortHandles');
    icOut2Line = get_param(icPorts.Outport(2), 'Line');
    assert(icOut2Line ~= -1, 'air:M0B:IcPitchLineMissing', ...
        'InputConditioning out 2 has no line.');
    innerPorts = get_param(acInner, 'PortHandles');
    delete_line(icOut2Line);
    add_block('simulink/Signal Routing/Demux', pitchDemux, ...
        'Position', [260, 610, 265, 650], 'Outputs', '2');

    % the original Roll_Pitch element is single precision: convert the M0-B
    % command to single so the switch keeps one consistent data type
    add_block('simulink/Signal Attributes/Data Type Conversion', pitchDtc, ...
        'Position', [330, 690, 370, 720], 'OutDataTypeStr', 'single');
    % arithmetic selector y = orig*(1-e) + m0b*e avoids the Switch control
    % port entirely; with e = 0 the original single-precision element is
    % reproduced bit-exactly (x*1.0 + 0.0*y = x in IEEE 754)
    add_block('simulink/Math Operations/Gain', enableNeg, ...
        'Position', [330, 750, 370, 780], 'Gain', '-1');
    add_block('simulink/Sources/Constant', oneConst, ...
        'Position', [330, 810, 360, 840], 'Value', '1');
    add_block('simulink/Math Operations/Sum', oneMinusE, ...
        'Position', [410, 760, 440, 820], 'Inputs', '++');
    add_block('simulink/Math Operations/Product', blendOrig, ...
        'Position', [480, 690, 510, 720], 'Inputs', '2');
    add_block('simulink/Math Operations/Product', blendM0b, ...
        'Position', [480, 760, 510, 790], 'Inputs', '2');
    add_block('simulink/Math Operations/Sum', blendSum, ...
        'Position', [550, 720, 580, 780], 'Inputs', '++');
    add_block('simulink/Signal Routing/Mux', pitchMux, ...
        'Position', [520, 610, 525, 650], 'Inputs', '2');
    add_line(acWrapper, icPorts.Outport(2), ...
        get_param(pitchDemux, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, ...
        get_param(pitchDemux, 'PortHandles').Outport(1), ...
        get_param(pitchMux, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, ...
        get_param(pitchDemux, 'PortHandles').Outport(2), ...
        get_param(blendOrig, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, get_param(loopIn, 'PortHandles').Outport(1), ...
        get_param(enableNeg, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, get_param(oneConst, 'PortHandles').Outport(1), ...
        get_param(oneMinusE, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, get_param(enableNeg, 'PortHandles').Outport(1), ...
        get_param(oneMinusE, 'PortHandles').Inport(2), 'autorouting', 'on');
    add_line(acWrapper, ...
        get_param(oneMinusE, 'PortHandles').Outport(1), ...
        get_param(blendOrig, 'PortHandles').Inport(2), 'autorouting', 'on');
    add_line(acWrapper, get_param(pitchIn, 'PortHandles').Outport(1), ...
        get_param(pitchDtc, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, get_param(pitchDtc, 'PortHandles').Outport(1), ...
        get_param(blendM0b, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, get_param(loopIn, 'PortHandles').Outport(1), ...
        get_param(blendM0b, 'PortHandles').Inport(2), 'autorouting', 'on');
    add_line(acWrapper, get_param(blendOrig, 'PortHandles').Outport(1), ...
        get_param(blendSum, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(acWrapper, get_param(blendM0b, 'PortHandles').Outport(1), ...
        get_param(blendSum, 'PortHandles').Inport(2), 'autorouting', 'on');
    add_line(acWrapper, get_param(blendSum, 'PortHandles').Outport(1), ...
        get_param(pitchMux, 'PortHandles').Inport(2), 'autorouting', 'on');
    add_line(acWrapper, get_param(pitchMux, 'PortHandles').Outport(1), ...
        innerPorts.Inport(3), 'autorouting', 'on');

    acRootPorts = get_param(acWrapper, 'PortHandles');
    add_line(model, ctlPorts.Outport(1), ...
        acRootPorts.Inport(13), 'autorouting', 'on');
    add_line(model, get_param(loopEnable, 'PortHandles').Outport(1), ...
        acRootPorts.Inport(14), 'autorouting', 'on');

    % one-step unit delay on the rate-limited v_ref feeding the override
    % (keeps the flags chain free of an algebraic loop)
    add_block('simulink/Discrete/Unit Delay', refDelay, ...
        'Position', [x0 - 420, y1 + 200, x0 - 380, y1 + 230], ...
        'InitialCondition', '0', 'SampleTime', '0.001');
    add_line(model, selPorts.Outport(1), ...
        get_param(refDelay, 'PortHandles').Inport(1), 'autorouting', 'on');

    % ---------- 6. plain-block override of flags 3 and 5 ----------
    % The M0-A flags chart stays untouched (its chart port set re-derives on
    % compilation and silently severs rewired lines). Bits 3 (attitude) and
    % 5 (speed miss) are recomputed with plain blocks and both thresholds
    % become runtime constants, which is the M0-B calibration deliverable.
    ov = [model '/M0B Flags Override'];
    add_block('built-in/Subsystem', ov, ...
        'Position', [x0 - 320, y1 + 120, x0 - 100, y1 + 320]);
    ovIn = {'flags_raw', 'att', 'v', 'v_ref'};
    for k = 1:numel(ovIn)
        add_block('built-in/Inport', [ov '/' ovIn{k}], ...
            'Position', [30, 33 + 30 * (k - 1), 60, 47 + 30 * (k - 1)], ...
            'Port', num2str(k));
    end
    add_block('built-in/Outport', [ov '/flags_out'], ...
        'Position', [470, 63, 500, 77], 'Port', '1');

    % bit 3: |phi| > att_tol || |theta| > att_tol
    add_block('simulink/Signal Routing/Demux', [ov '/Att Demux'], ...
        'Position', [120, 60, 125, 110], 'Outputs', '6');
    add_block('simulink/Math Operations/Abs', [ov '/Phi Abs'], ...
        'Position', [180, 55, 210, 75]);
    add_block('simulink/Math Operations/Abs', [ov '/Theta Abs'], ...
        'Position', [180, 95, 210, 115]);
    add_block('simulink/Logic and Bit Operations/Relational Operator', ...
        [ov '/Phi Cmp'], 'Position', [260, 50, 300, 80], 'Operator', '>');
    add_block('simulink/Logic and Bit Operations/Relational Operator', ...
        [ov '/Theta Cmp'], 'Position', [260, 95, 300, 125], 'Operator', '>');
    add_block('simulink/Logic and Bit Operations/Logical Operator', ...
        [ov '/Att Flag OR'], 'Position', [340, 70, 370, 105], ...
        'Operator', 'OR', 'Inputs', '2');
    add_block('simulink/Signal Attributes/Data Type Conversion', ...
        [ov '/Att Flag Dbl'], 'Position', [390, 75, 430, 100], ...
        'OutDataTypeStr', 'double');
    add_block('built-in/Inport', [ov '/att_tol_in'], ...
        'Position', [30, 183, 60, 197], 'Port', '5');
    % bit 5: |v - v_ref| > speed_tol
    add_block('simulink/Math Operations/Sum', [ov '/Speed Diff'], ...
        'Position', [120, 160, 150, 190], 'Inputs', '+-');
    add_block('simulink/Math Operations/Abs', [ov '/Speed Abs'], ...
        'Position', [180, 165, 210, 185]);
    add_block('simulink/Logic and Bit Operations/Relational Operator', ...
        [ov '/Speed Cmp'], 'Position', [260, 160, 300, 190], 'Operator', '>');
    add_block('simulink/Signal Attributes/Data Type Conversion', ...
        [ov '/Speed Flag Dbl'], 'Position', [340, 165, 380, 185], ...
        'OutDataTypeStr', 'double');
    add_block('built-in/Inport', [ov '/speed_tol_in'], ...
        'Position', [30, 228, 60, 242], 'Port', '6');
    % assembly: pass through bits 1,2,4,6,7,8 and replace 3,5
    add_block('simulink/Signal Routing/Demux', [ov '/Flags Demux'], ...
        'Position', [120, 260, 125, 360], 'Outputs', '8');
    add_block('simulink/Signal Routing/Mux', [ov '/Flags Mux'], ...
        'Position', [420, 250, 425, 360], 'Inputs', '8');

    ovPorts = get_param(ov, 'PortHandles');
    attDemuxP = get_param([ov '/Att Demux'], 'PortHandles');
    phiAbsP = get_param([ov '/Phi Abs'], 'PortHandles');
    thAbsP = get_param([ov '/Theta Abs'], 'PortHandles');
    phiCmpP = get_param([ov '/Phi Cmp'], 'PortHandles');
    thCmpP = get_param([ov '/Theta Cmp'], 'PortHandles');
    orP = get_param([ov '/Att Flag OR'], 'PortHandles');
    orDblP = get_param([ov '/Att Flag Dbl'], 'PortHandles');
    spDiffP = get_param([ov '/Speed Diff'], 'PortHandles');
    spAbsP = get_param([ov '/Speed Abs'], 'PortHandles');
    spCmpP = get_param([ov '/Speed Cmp'], 'PortHandles');
    spDblP = get_param([ov '/Speed Flag Dbl'], 'PortHandles');
    fdP = get_param([ov '/Flags Demux'], 'PortHandles');
    fmP = get_param([ov '/Flags Mux'], 'PortHandles');

    add_line(ov, get_param([ov '/att'], 'PortHandles').Outport(1), ...
        attDemuxP.Inport(1), 'autorouting', 'on');
    add_line(ov, attDemuxP.Outport(1), phiAbsP.Inport(1), 'autorouting', 'on');
    add_line(ov, attDemuxP.Outport(2), thAbsP.Inport(1), 'autorouting', 'on');
    add_line(ov, phiAbsP.Outport(1), phiCmpP.Inport(1), 'autorouting', 'on');
    add_line(ov, thAbsP.Outport(1), thCmpP.Inport(1), 'autorouting', 'on');
    add_line(ov, get_param([ov '/att_tol_in'], 'PortHandles').Outport(1), ...
        phiCmpP.Inport(2), 'autorouting', 'on');
    add_line(ov, get_param([ov '/att_tol_in'], 'PortHandles').Outport(1), ...
        thCmpP.Inport(2), 'autorouting', 'on');
    add_line(ov, phiCmpP.Outport(1), orP.Inport(1), 'autorouting', 'on');
    add_line(ov, thCmpP.Outport(1), orP.Inport(2), 'autorouting', 'on');
    add_line(ov, orP.Outport(1), orDblP.Inport(1), 'autorouting', 'on');
    add_line(ov, get_param([ov '/v'], 'PortHandles').Outport(1), ...
        spDiffP.Inport(1), 'autorouting', 'on');
    add_line(ov, get_param([ov '/v_ref'], 'PortHandles').Outport(1), ...
        spDiffP.Inport(2), 'autorouting', 'on');
    add_line(ov, spDiffP.Outport(1), spAbsP.Inport(1), 'autorouting', 'on');
    add_line(ov, spAbsP.Outport(1), spCmpP.Inport(1), 'autorouting', 'on');
    add_line(ov, get_param([ov '/speed_tol_in'], 'PortHandles').Outport(1), ...
        spCmpP.Inport(2), 'autorouting', 'on');
    add_line(ov, spCmpP.Outport(1), spDblP.Inport(1), 'autorouting', 'on');
    add_line(ov, get_param([ov '/flags_raw'], 'PortHandles').Outport(1), ...
        fdP.Inport(1), 'autorouting', 'on');
    muxFeeds = {fdP.Outport(1), fdP.Outport(2), orDblP.Outport(1), ...
        fdP.Outport(4), spDblP.Outport(1), fdP.Outport(6), ...
        fdP.Outport(7), fdP.Outport(8)};
    for k = 1:8
        add_line(ov, muxFeeds{k}, fmP.Inport(k), 'autorouting', 'on');
    end
    add_line(ov, fmP.Outport(1), ...
        get_param([ov '/flags_out'], 'PortHandles').Inport(1), ...
        'autorouting', 'on');
    add_block('simulink/Sinks/Terminator', [ov '/Term Bit3'], ...
        'Position', [180, 300, 210, 315]);
    add_block('simulink/Sinks/Terminator', [ov '/Term Bit5'], ...
        'Position', [180, 330, 210, 345]);
    add_line(ov, fdP.Outport(3), ...
        get_param([ov '/Term Bit3'], 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(ov, fdP.Outport(5), ...
        get_param([ov '/Term Bit5'], 'PortHandles').Inport(1), 'autorouting', 'on');

    % root sources for the override subsystem
    spTolConst = [model '/M0B Speed Tol'];
    add_block('simulink/Sources/Constant', spTolConst, ...
        'Position', [x0 + 500, y1 - 120, x0 + 530, y1 - 90], 'Value', '1.0');
    attObsRootPort = get_param(acWrapper, 'PortHandles').Outport(3);
    add_line(model, get_param(flagsBlock, 'PortHandles').Outport(1), ...
        ovPorts.Inport(1), 'autorouting', 'on');       % flags_raw
    add_line(model, attObsRootPort, ovPorts.Inport(2), ...
        'autorouting', 'on');                          % att (6)
    add_line(model, get_param(vZoh, 'PortHandles').Outport(1), ...
        ovPorts.Inport(3), 'autorouting', 'on');       % v (1 ms)
    add_line(model, get_param(refDelay, 'PortHandles').Outport(1), ...
        ovPorts.Inport(4), 'autorouting', 'on');       % v_ref delayed
    add_line(model, get_param(attTolConst, 'PortHandles').Outport(1), ...
        ovPorts.Inport(5), 'autorouting', 'on');       % att_tol
    add_line(model, get_param(spTolConst, 'PortHandles').Outport(1), ...
        ovPorts.Inport(6), 'autorouting', 'on');       % speed_tol


    % ---------- 7. m0b log bus ----------
    add_block('simulink/Signal Routing/Mux', busMux, ...
        'Inputs', '7', 'Position', [x0 + 680, y1 + 100, x0 + 690, y1 + 220]);
    busPorts = get_param(busMux, 'PortHandles');
    add_line(model, selPorts.Outport(1), busPorts.Inport(1), ...
        'autorouting', 'on');                                     % v_ref
    add_line(model, ctlPorts.Outport(1), busPorts.Inport(2), ...
        'autorouting', 'on');                                     % pitch_cmd
    add_line(model, ctlPorts.Outport(2), busPorts.Inport(3), ...
        'autorouting', 'on');                                     % v_err
    add_line(model, selPorts.Outport(2), busPorts.Inport(4), ...
        'autorouting', 'on');                                     % status
    add_line(model, get_param(loopEnable, 'PortHandles').Outport(1), ...
        busPorts.Inport(5), 'autorouting', 'on');                 % enable
    add_line(model, get_param(vexZoh, 'PortHandles').Outport(1), ...
        busPorts.Inport(6), 'autorouting', 'on');                 % ve_x
    add_line(model, get_param(vZoh, 'PortHandles').Outport(1), ...
        busPorts.Inport(7), 'autorouting', 'on');                 % v
    add_block('simulink/Sinks/To Workspace', logBus, ...
        'Position', [x0 + 760, y1 + 130, x0 + 930, y1 + 160], ...
        'VariableName', 'm0b_log_bus', 'SaveFormat', 'Timeseries');
    add_line(model, busPorts.Outport(1), ...
        get_param(logBus, 'PortHandles').Inport(1), 'autorouting', 'on');

    % re-point every consumer of the raw flags to the overridden output:
    % the M0-A log bus (in 8), the selector (in 4) and the To Workspace sink
    flagsSrc = get_param(flagsBlock, 'PortHandles').Outport(1);
    l = get_param(flagsSrc, 'Line');
    dsts = get_param(l, 'DstPortHandle');
    for m = 1:numel(dsts)
        delete_line(model, flagsSrc, dsts(m));
    end
    ovOut = ovPorts.Outport(1);
    add_line(model, ovOut, ...
        get_param([model '/M0A Log Bus'], 'PortHandles').Inport(8), ...
        'autorouting', 'on');
    add_line(model, ovOut, selPorts.Inport(4), 'autorouting', 'on');
    add_line(model, ovOut, get_param([model '/M0A Log Constraint Flags'], ...
        'PortHandles').Inport(1), 'autorouting', 'on');

    set_param(model, 'SimulationCommand', 'update');
    % final re-check of the M0-B chart input lines after the last update
    for k = 1:numel(selIn)
        ensureLine(model, selBlock, selIn{k}, 'M0B Ref Safety Core', k);
    end
    for k = 1:numel(ctlIn)
        ensureLine(model, ctrlBlock, ctlIn{k}, 'M0B Speed Core', k);
    end

    % ---------- functional verification before saving ----------
    % enable the loop in memory and confirm the pitch command actually
    % reaches the vehicle (ve_x must leave zero) before the model is saved
    set_param(loopEnable, 'Value', '1');
    checkOut = sim(model);
    checkVeX = squeeze(checkOut.get('m0b_log_bus').Data);
    if size(checkVeX, 1) == 7
        checkVeX = checkVeX';
    end
    vexTail = mean(checkVeX(6001:10001, 6));
    thetaAll = double(squeeze(checkOut.get('m0a_log_bus').Data));
    if size(thetaAll, 1) == 35
        thetaAll = thetaAll';
    end
    thetaTail = mean(thetaAll(6001:10001, 6));
    assert(abs(vexTail) > 0.5, 'air:M0B:InjectionBroken', ...
        'speed-loop pitch command did not reach the vehicle (ve_x tail %.3f).', vexTail);
    fprintf('functional check: ve_x tail mean %.3f m/s, theta tail %.4f rad\n', ...
        vexTail, thetaTail);
    set_param(loopEnable, 'Value', '0');
    set_param(model, 'SimulationCommand', 'update');
    save_system(model);

    % ---------- scenario config archive ----------
    stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    cfgDir = fullfile(wsRoot, 'results', 'm0b_config', stamp);
    if ~exist(cfgDir, 'dir')
        mkdir(cfgDir);
    end
    cfg = struct( ...
        'model', "air_spare", ...
        'stage', "M0-B", ...
        'speed_loop_enable', 0, ...
        'optimizer_enable', 0, ...
        'v_ref_manual_mps', 5.0, ...
        'v_ref_optimizer_mps', 5.0, ...
        'v_ref_range', [0.0 15.0], ...
        'v_ref_rate_limit_mps2', 2.0, ...
        'hold_max_s', 0.5, 'clear_max_s', 1.5, ...
        'Kp', 0.06, 'Ki', 0.02, ...
        'pitch_cmd_max', 0.40, 'pitch_rate_max', 0.25, 'integ_max', 0.15, ...
        'flag5_semantics', "|v - v_ref(delayed)| > 1.0 m/s", ...
        'm0b_bus_layout', "[v_ref, pitch_cmd, v_err, optimizer_status, speed_loop_enable, ve_x, v]");
    save(fullfile(cfgDir, 'm0b_config.mat'), 'cfg');
    cfgLines = { ...
        "model: air_spare", "stage: M0-B", ...
        "speed_loop_enable: 0 (bypass; bit-exact M0-A behaviour)", ...
        "optimizer_enable: 0", ...
        "v_ref_manual_mps: 5.0", "v_ref_optimizer_mps: 5.0 (M0-C placeholder)", ...
        "v_ref_range_mps: [0 15]", "v_ref_rate_limit_mps2: 2.0", ...
        "safety: hold_max_s=0.5 clear_max_s=1.5 hard_flags=[1 2 3 4 6 7]", ...
        "controller: Kp=0.06 Ki=0.02 pitch_cmd_max=0.40 pitch_rate_max=0.25 integ_max=0.15", ...
        "sign_convention: pitch_cmd>0 -> theta_des>0 -> thrust tilts against +Ve_x", ...
        "flag5: |v - v_ref(unit-delayed)| > 1.0 m/s", ...
        "m0b_log_bus(7): [v_ref, pitch_cmd, v_err, optimizer_status, speed_loop_enable, ve_x, v]"};
    writelines(string(cfgLines), fullfile(cfgDir, 'm0b_config.txt'));

    result = struct( ...
        'model', model, ...
        'selectorBlock', string(selBlock), ...
        'controllerBlock', string(ctrlBlock), ...
        'busVariable', "m0b_log_bus", ...
        'configDir', string(cfgDir));
    fprintf('M0-B speed loop PASS: %s\n', model);
    fprintf('Defaults: speed_loop_enable=0 optimizer_enable=0 (baseline passthrough)\n');
    fprintf('Logged: m0b_log_bus (7)\n');
    fprintf('Config archived: %s\n', cfgDir);
catch err
    if strcmp(dirtyBefore, 'off') && bdIsLoaded(model)
        close_system(model, 0);
        load_system(fullfile(modelDir, [model '.slx']));
    end
    rethrow(err);
end
end

function ensureLine(rootModel, sysName, srcName, dstName, dstPort)
%ENSURELINE Add sysName/srcName -> sysName/dstName#dstPort until it survives
%   a diagram update. Verified wiring only; works for Inport blocks, plain
%   blocks and charts (single-output sources).
    for attempt = 1:6
        dstPh = get_param(sprintf('%s/%s', sysName, dstName), 'PortHandles');
        l = get_param(dstPh.Inport(dstPort), 'Line');
        if l ~= -1
            srcParent = getfullname(get_param(get_param(l, 'SrcPortHandle'), 'Parent'));
            if strcmp(srcParent, sprintf('%s/%s', sysName, srcName))
                return;
            end
            delete_line(l);
        end
        srcPh = get_param(sprintf('%s/%s', sysName, srcName), 'PortHandles');
        add_line(sysName, srcPh.Outport(1), ...
            dstPh.Inport(dstPort), 'autorouting', 'on');
        try
            set_param(rootModel, 'SimulationCommand', 'update');
        catch e
            if attempt == 6
                rethrow(e);
            end
        end
    end
    error('air:M0B:LineUnstable', ...
        'line %s/%s -> %s#%d did not survive the diagram update.', ...
        sysName, srcName, dstName, dstPort);
end

function tf = isBlock(path)
try
    get_param(path, 'Handle');
    tf = true;
catch
    tf = false;
end
end
