function result = add_air_m0a_constraints_and_logbus()
%ADD_AIR_M0A_CONSTRAINTS_AND_LOGBUS Add constraint flags, unified log bus and
% the fixed baseline mode switch (optimizer_enable = 0). Works only on
% air_spare.slx and only after add_air_m0a_power_measurement.
%
%   Branch points (all non-invasive taps on existing nets):
%     - euler angles: outputs of Attitude Control/quat2eul (phi, theta, psi)
%     - body rates p/q/r: input line #5 (pqr) of the control_and_mix chart
%       inside Attitude Control/AttitudeControl, per its verified signature
%       (phi, theta, roll_pitch, yaw, pqr, Thrust, dt, arm)
%     - horizontal speed v: existing M0A Horizontal Speed Fcn inside Subsystem
%     - pwm vector / P_est: outputs of the M0-A power stage (4 ms rate),
%       resampled to the 1 ms solver grid via Zero-Order Hold blocks
%
%   Constraint flags (placeholder thresholds, to be tuned in M0-B):
%     1 pwm saturation   2 rpm saturation   3 attitude excess
%     4 yaw-rate excess  5 speed miss (v_ref = 0 placeholder)
%     6 power anomaly    7 signal missing (NaN)   8 reserved
%
%   Unified log bus layout (35, all double, 1 ms):
%     [v, P_est, E_est, power_source, att(6) = phi theta psi p q r,
%      pwm(8), rpm_est(8), constraint_flags(8), optimizer_enable]

model = 'air_spare';
modelDir = fileparts(mfilename('fullpath'));
wasLoaded = bdIsLoaded(model);
if ~wasLoaded
    load_system(fullfile(modelDir, [model '.slx']));
end
dirtyBefore = get_param(model, 'Dirty');

try
    set_param(model, 'SimulationCommand', 'update');

    acWrapper = [model '/Attitude Control'];
    acInner = [acWrapper '/AttitudeControl'];
    subSystem = [model '/Subsystem'];
    powerBlock = [model '/M0A Power Measurement'];
    pwmConvert = [model '/M0A PWM Vector Double'];

    attMux = [acWrapper '/M0A Attitude Rate Vector'];
    attOut = [acWrapper '/M0A Attitude Obs Out'];
    vOut = [subSystem '/M0A Speed Obs Out'];
    pwmZoh = [model '/M0A PWM ZOH 1ms'];
    pZoh = [model '/M0A P Est ZOH 1ms'];
    rpmFcn = [model '/M0A Bus RPM Est'];
    flagsBlock = [model '/M0A Constraint Flags'];
    flagsCore = [flagsBlock '/M0A Flags Core'];
    enableConst = [model '/M0A Optimizer Enable'];
    busMux = [model '/M0A Log Bus'];
    logBus = [model '/M0A Log Log Bus'];
    logFlags = [model '/M0A Log Constraint Flags'];
    logEnable = [model '/M0A Log Optimizer Enable'];
    targets = {attMux, attOut, vOut, pwmZoh, pZoh, rpmFcn, flagsBlock, ...
        enableConst, busMux, logBus, logFlags, logEnable};
    assert(~any(cellfun(@isBlock, targets)), ...
        'air:M0A:AlreadyInstalled', ...
        'M0-A constraint/log-bus blocks already exist. No changes were made.');
    assert(isBlock(pwmConvert) && isBlock(powerBlock), ...
        'air:M0A:PowerStageMissing', ...
        'Run add_air_m0a_power_measurement first.');

    % --- locate branch sources inside Attitude Control wrapper ---
    quatBlock = [acWrapper '/quat2eul'];
    assert(isBlock(quatBlock), 'air:M0A:QuatBlockMissing', ...
        'quat2eul block not found in Attitude Control.');
    innerCharts = find(sfroot, '-isa', 'Stateflow.EMChart');
    innerChartPath = '';
    for k = 1:numel(innerCharts)
        if strncmp(innerCharts(k).Path, [acInner '/'], numel(acInner) + 1)
            innerChartPath = innerCharts(k).Path;
        end
    end
    assert(~isempty(innerChartPath), 'air:M0A:ControlChartMissing', ...
        'control_and_mix chart not found inside AttitudeControl.');
    chartBlockPorts = get_param(innerChartPath, 'PortHandles');

    quatPorts = get_param(quatBlock, 'PortHandles');
    assert(numel(quatPorts.Outport) == 3, ...
        'air:M0A:UnexpectedQuatPorts', ...
        'Expected three quat2eul outputs; found %d.', numel(quatPorts.Outport));
    assert(numel(chartBlockPorts.Inport) == 8, ...
        'air:M0A:UnexpectedChartPorts', ...
        'Expected eight control_and_mix inputs; found %d.', ...
        numel(chartBlockPorts.Inport));

    % --- inside AttitudeControl: branch pqr (chart arg #5) to new outport 9 ---
    chartPos = get_param(innerChartPath, 'Position');
    pqOutInner = [acInner '/M0A Pqr Out'];
    add_block('built-in/Outport', pqOutInner, ...
        'Position', [chartPos(3) + 120, chartPos(2) + 130, chartPos(3) + 150, chartPos(2) + 144], ...
        'Port', '9');
    pqrLine = get_param(chartBlockPorts.Inport(5), 'Line');
    assert(pqrLine ~= -1, 'air:M0A:PqrLineMissing', ...
        'control_and_mix input #5 (pqr) has no incoming line.');
    pqrSrc = get_param(pqrLine, 'SrcPortHandle');
    add_line(acInner, pqrSrc, ...
        get_param(pqOutInner, 'PortHandles').Inport(1), 'autorouting', 'on');

    % --- inside Attitude Control: mux euler + pqr, new wrapper outport 3 ---
    qpos = get_param(quatBlock, 'Position');
    add_block('simulink/Signal Routing/Mux', attMux, ...
        'Inputs', '4', 'Position', [qpos(3) + 260, qpos(2), qpos(3) + 270, qpos(2) + 120]);
    attMuxPorts = get_param(attMux, 'PortHandles');
    add_block('built-in/Outport', attOut, ...
        'Position', [qpos(3) + 340, qpos(2) + 45, qpos(3) + 370, qpos(2) + 75], ...
        'Port', '3');
    for k = 1:3
        add_line(acWrapper, quatPorts.Outport(k), attMuxPorts.Inport(k), ...
            'autorouting', 'on');
    end
    add_line(acWrapper, get_param(acInner, 'PortHandles').Outport(9), ...
        attMuxPorts.Inport(4), 'autorouting', 'on');
    add_line(acWrapper, attMuxPorts.Outport(1), ...
        get_param(attOut, 'PortHandles').Inport(1), 'autorouting', 'on');

    % --- inside Subsystem: branch horizontal speed to new outport 8 ---
    hSpeed = [subSystem '/M0A Horizontal Speed'];
    assert(isBlock(hSpeed), 'air:M0A:SpeedBlockMissing', ...
        'M0A Horizontal Speed not found; run the velocity observability script first.');
    hsPos = get_param(hSpeed, 'Position');
    add_block('built-in/Outport', vOut, ...
        'Position', [hsPos(3) + 220, hsPos(2) + 10, hsPos(3) + 250, hsPos(2) + 24], ...
        'Port', '8');
    add_line(subSystem, get_param(hSpeed, 'PortHandles').Outport(1), ...
        get_param(vOut, 'PortHandles').Inport(1), 'autorouting', 'on');

    % --- root-level source ports for the observation branches ---
    attObsRoot = get_param(acWrapper, 'PortHandles').Outport(3);
    vObsRoot = get_param(subSystem, 'PortHandles').Outport(8);

    % --- root: rate alignment to the 1 ms solver grid ---
    demuxPosition = get_param([model '/Demux'], 'Position');
    x0 = demuxPosition(3) + 200;
    y0 = demuxPosition(4) + 480;

    add_block('simulink/Discrete/Zero-Order Hold', pwmZoh, ...
        'Position', [x0, y0, x0 + 40, y0 + 30], 'SampleTime', '0.001');
    add_block('simulink/Discrete/Zero-Order Hold', pZoh, ...
        'Position', [x0, y0 + 60, x0 + 40, y0 + 90], 'SampleTime', '0.001');
    add_line(model, get_param(pwmConvert, 'PortHandles').Outport(1), ...
        get_param(pwmZoh, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, get_param(powerBlock, 'PortHandles').Outport(1), ...
        get_param(pZoh, 'PortHandles').Inport(1), 'autorouting', 'on');

    % bus rpm estimate: same documented mapping as the actuator script
    add_block('simulink/User-Defined Functions/Fcn', rpmFcn, ...
        'Position', [x0 + 90, y0, x0 + 275, y0 + 30], ...
        'Expr', '9.54929658551372*(u-1000)');
    add_line(model, get_param(pwmZoh, 'PortHandles').Outport(1), ...
        get_param(rpmFcn, 'PortHandles').Inport(1), 'autorouting', 'on');

    % --- M0A Constraint Flags subsystem ---
    add_block('built-in/Subsystem', flagsBlock, ...
        'Position', [x0 + 120, y0 + 120, x0 + 300, y0 + 260]);
    add_block('built-in/Inport', [flagsBlock '/pwm_us'], ...
        'Position', [30, 33, 60, 47], 'Port', '1');
    add_block('built-in/Inport', [flagsBlock '/attitude'], ...
        'Position', [30, 78, 60, 92], 'Port', '2');
    add_block('built-in/Inport', [flagsBlock '/v'], ...
        'Position', [30, 123, 60, 137], 'Port', '3');
    add_block('built-in/Inport', [flagsBlock '/P_est'], ...
        'Position', [30, 168, 60, 182], 'Port', '4');
    add_block('built-in/Inport', [flagsBlock '/E_est'], ...
        'Position', [30, 213, 60, 227], 'Port', '5');
    add_block('simulink/User-Defined Functions/MATLAB Function', flagsCore, ...
        'Position', [120, 90, 290, 150]);
    rt = sfroot;
    fchart = find(rt, '-isa', 'Stateflow.EMChart', 'Path', flagsCore);
    assert(numel(fchart) == 1, 'air:M0A:ChartNotFound', ...
        'Cannot locate the MATLAB Function chart at %s.', flagsCore);
    fchart.Script = [ ...
        'function flags = fcn(pwm_us, att, v, P_est, E_est)' newline ...
        '% Eight M0-A constraint flags (0/1). Thresholds are documented' newline ...
        '% placeholders pending calibration; tune them in M0-B.' newline ...
        'att_tol = 0.523;   % rad, 30 deg, same bound as controller phi/theta cmd' newline ...
        'yaw_rate_tol = 1.5; % rad/s, same bound as controller r_des' newline ...
        'speed_tol = 1.0;   % m/s, vs placeholder v_ref = 0 (no speed loop yet)' newline ...
        'P_max = 1500.0;    % W, uncalibrated placeholder' newline ...
        'pwm_edge = 5.0;    % us margin from the 1000/2000 rails' newline ...
        'om = pwm_us - 1000.0;' newline ...
        'flags = zeros(1, 8);' newline ...
        'flags(1) = any(pwm_us <= 1000.0 + pwm_edge) || any(pwm_us >= 2000.0 - pwm_edge);' newline ...
        'flags(2) = any(om <= pwm_edge) || any(om >= 1000.0 - pwm_edge);' newline ...
        'flags(3) = abs(att(1)) > att_tol || abs(att(2)) > att_tol;' newline ...
        'flags(4) = abs(att(6)) > yaw_rate_tol;' newline ...
        'flags(5) = abs(v) > speed_tol; % v_ref = 0 placeholder until M0-B' newline ...
        'flags(6) = P_est < 0.0 || P_est > P_max;' newline ...
        'flags(7) = any(isnan([pwm_us(:); att(:); v; P_est; E_est]));' newline ...
        'flags(8) = 0.0; % reserved' newline ...
        'end'];
    add_block('built-in/Outport', [flagsBlock '/flags'], ...
        'Position', [380, 113, 410, 127], 'Port', '1');
    inportNames = {'pwm_us', 'attitude', 'v', 'P_est', 'E_est'};
    for k = 1:5
        add_line(flagsBlock, ...
            get_param([flagsBlock '/' inportNames{k}], 'PortHandles').Outport(1), ...
            get_param(flagsCore, 'PortHandles').Inport(k), 'autorouting', 'on');
    end
    add_line(flagsBlock, get_param(flagsCore, 'PortHandles').Outport(1), ...
        get_param([flagsBlock '/flags'], 'PortHandles').Inport(1), 'autorouting', 'on');

    flagPorts = get_param(flagsBlock, 'PortHandles');
    add_line(model, get_param(pwmZoh, 'PortHandles').Outport(1), ...
        flagPorts.Inport(1), 'autorouting', 'on');
    add_line(model, attObsRoot, ...
        flagPorts.Inport(2), 'autorouting', 'on');
    add_line(model, vObsRoot, ...
        flagPorts.Inport(3), 'autorouting', 'on');
    add_line(model, get_param(pZoh, 'PortHandles').Outport(1), ...
        flagPorts.Inport(4), 'autorouting', 'on');
    add_line(model, get_param(powerBlock, 'PortHandles').Outport(2), ...
        flagPorts.Inport(5), 'autorouting', 'on');

    % --- optimizer_enable = 0 fixed baseline mode ---
    add_block('simulink/Sources/Constant', enableConst, ...
        'Position', [x0 + 120, y0 + 330, x0 + 150, y0 + 360], 'Value', '0');

    % --- unified log bus (35 wide, 1 ms) ---
    add_block('simulink/Signal Routing/Mux', busMux, ...
        'Inputs', '9', 'Position', [x0 + 520, y0 + 100, x0 + 530, y0 + 260]);
    busPorts = get_param(busMux, 'PortHandles');
    add_line(model, vObsRoot, ...
        busPorts.Inport(1), 'autorouting', 'on');                              % v
    add_line(model, get_param(pZoh, 'PortHandles').Outport(1), ...
        busPorts.Inport(2), 'autorouting', 'on');                              % P_est
    add_line(model, get_param(powerBlock, 'PortHandles').Outport(2), ...
        busPorts.Inport(3), 'autorouting', 'on');                              % E_est
    add_line(model, get_param(powerBlock, 'PortHandles').Outport(3), ...
        busPorts.Inport(4), 'autorouting', 'on');                              % source
    add_line(model, attObsRoot, ...
        busPorts.Inport(5), 'autorouting', 'on');                              % att(6)
    add_line(model, get_param(pwmZoh, 'PortHandles').Outport(1), ...
        busPorts.Inport(6), 'autorouting', 'on');                              % pwm(8)
    add_line(model, get_param(rpmFcn, 'PortHandles').Outport(1), ...
        busPorts.Inport(7), 'autorouting', 'on');                              % rpm(8)
    add_line(model, flagPorts.Outport(1), ...
        busPorts.Inport(8), 'autorouting', 'on');                              % flags(8)
    add_line(model, get_param(enableConst, 'PortHandles').Outport(1), ...
        busPorts.Inport(9), 'autorouting', 'on');                              % enable

    add_block('simulink/Sinks/To Workspace', logBus, ...
        'Position', [x0 + 620, y0 + 130, x0 + 790, y0 + 160], ...
        'VariableName', 'm0a_log_bus', 'SaveFormat', 'Timeseries');
    add_block('simulink/Sinks/To Workspace', logFlags, ...
        'Position', [x0 + 380, y0 + 210, x0 + 550, y0 + 240], ...
        'VariableName', 'm0a_constraint_flags', 'SaveFormat', 'Timeseries');
    add_block('simulink/Sinks/To Workspace', logEnable, ...
        'Position', [x0 + 240, y0 + 335, x0 + 410, y0 + 365], ...
        'VariableName', 'm0a_optimizer_enable', 'SaveFormat', 'Timeseries');
    add_line(model, busPorts.Outport(1), ...
        get_param(logBus, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, flagPorts.Outport(1), ...
        get_param(logFlags, 'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, get_param(enableConst, 'PortHandles').Outport(1), ...
        get_param(logEnable, 'PortHandles').Inport(1), 'autorouting', 'on');

    set_param(model, 'SimulationCommand', 'update');
    save_system(model);

    % --- scenario config archive ---
    stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
    cfgDir = fullfile(modelDir, 'results', 'm0a_config', stamp);
    if ~exist(cfgDir, 'dir')
        mkdir(cfgDir);
    end
    cfg = struct( ...
        'model', "air_spare", ...
        'stage', "M0-A", ...
        'optimizer_enable', 0, ...
        'power_source', "estimated (flag 0, uncalibrated)", ...
        'solverStep_s', 0.001, ...
        'stopTime_s', 10, ...
        'busLayout', "[v, P_est, E_est, power_source, att(6)=phi theta psi p q r, pwm(8), rpm_est(8), flags(8), optimizer_enable]", ...
        'flagThresholds', struct('att_tol_rad', 0.523, 'yaw_rate_tol_rad_s', 1.5, ...
            'speed_tol_mps', 1.0, 'P_max_W', 1500.0, 'pwm_edge_us', 5.0), ...
        'notes', "v_ref placeholder = 0 until M0-B; thresholds uncalibrated");
    save(fullfile(cfgDir, 'm0a_scenario_config.mat'), 'cfg');
    cfgLines = { ...
        "model: air_spare", "stage: M0-A", "optimizer_enable: 0", ...
        "power_source: estimated (flag 0, uncalibrated)", ...
        "solver_step_s: 0.001", "stop_time_s: 10", ...
        "bus_layout: [v, P_est, E_est, power_source, att(6)=phi theta psi p q r, pwm(8), rpm_est(8), flags(8), optimizer_enable]", ...
        "flag_thresholds: att_tol_rad=0.523 yaw_rate_tol_rad_s=1.5 speed_tol_mps=1.0 P_max_W=1500 pwm_edge_us=5", ...
        "notes: v_ref placeholder = 0 until M0-B; thresholds uncalibrated"};
    writelines(string(cfgLines), fullfile(cfgDir, 'm0a_scenario_config.txt'));

    result = struct( ...
        'model', model, ...
        'flagsBlock', string(flagsBlock), ...
        'busVariable', "m0a_log_bus", ...
        'flagsVariable', "m0a_constraint_flags", ...
        'enableVariable', "m0a_optimizer_enable", ...
        'configDir', string(cfgDir));
    fprintf('M0-A constraints and log bus PASS: %s\n', model);
    fprintf('Logged: m0a_log_bus (35), m0a_constraint_flags (8), m0a_optimizer_enable\n');
    fprintf('Config archived: %s\n', cfgDir);
catch err
    if strcmp(dirtyBefore, 'off') && bdIsLoaded(model)
        close_system(model, 0);
        load_system(fullfile(modelDir, [model '.slx']));
    end
    rethrow(err);
end
end

function tf = isBlock(path)
try
    get_param(path, 'Handle');
    tf = true;
catch
    tf = false;
end
end

