%ADD_AIR_M2_ALLOCATOR install the M2 eta allocator + ESC into air_spare.
%   Splices the constrained PWM-domain coaxial-ratio allocator
%   (m2_eta_allocator) into the single 8-channel pwm fan-out of
%   'Attitude Control' out 2, and wires the wrapped ratio kernel
%   (m2_eta_esc -> ratioesc.esc_step) as the eta_ref source (plan:
%   docs/interfaces/M2_ETA_ALLOCATOR.md section 5).
%
%   New blocks: 'M2 Clock' (Digital Clock 0.05 s), 'M2 ESC Input' (mux,
%   35-wide = 1+1+1+1+6+8+8+8+1), 'M2 Eta ESC' (Interpreted MATLAB Fcn,
%   explicit 0.05 s), per-input 0.05 s ZOHs (v/P/E/att/flags reuse the
%   M0-C ZOHs by branching), 'M2 PWM ZOH' / 'M2 RPM ZOH',
%   'M2 Pwm Conv' (double)
%   (0.004 s explicit rate change), 'M2 Eta Allocator' (Interpreted
%   MATLAB Fcn, rate inherited, outputs pwm8/sat/dmz), 'M2 Sat ZOH' +
%   'M2 Dmz ZOH' (0.05 s), 'M2 Eta Log' (mux 4) -> 'M2 Log Eta Bus'
%   (ToWorkspace m2_eta_log).
%
%   Environment rules honoured (M0C_SPEED_ESC.md section 2.3 patterns):
%   per-branch line deletion only; pre-save functional simulation;
%   re-ensure of ALL chart feed lines after the simulation; post-save
%   disk reload with source-port-handle link assertions; dirty-model
%   guard; automatic restore of the pre-install backup on any failure.

model = 'air_spare';
modelDir = fileparts(mfilename('fullpath'));
wsRoot = fileparts(fileparts(modelDir));
ratioRoot = fullfile(wsRoot, 'modules', 'ratio_esc');
if ~isfolder(ratioRoot)
    ratioRoot = fullfile(wsRoot, '26isip_Aerospace', 'modules', 'ratio_esc');
end
assert(isfolder(ratioRoot), 'air:M2:KernelMissing', ...
    'ratio_esc module not found relative to %s.', modelDir);
addpath(ratioRoot);

global M2_ETA_PARAMS % compile-probe safe defaults (fixed 1.0 = identity)
M2_ETA_PARAMS = [];

stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
cfgDir = fullfile(wsRoot, 'results', 'm2_config', stamp);

wasLoaded = bdIsLoaded(model);
if ~wasLoaded
    load_system(fullfile(modelDir, [model '.slx']));
end
dirtyBefore = get_param(model, 'Dirty');
if strcmp(dirtyBefore, 'on')
    error('air:M2:DirtyModel', ['air_spare has unsaved changes. Save or ' ...
        'discard them explicitly before running add_air_m2_allocator; ' ...
        'no model changes were made.']);
end

try
    set_param(model, 'SimulationCommand', 'update');

    if isBlock([model '/M2 Eta Allocator']) || ...
            isBlock([model '/M2 Eta ESC']) || ...
            isBlock([model '/M2 Pwm Conv'])
        error('air:M2:AlreadyInstalled', ...
            'M2 blocks already exist. No changes were made.');
    end

    ac = [model '/Attitude Control'];
    demuxBlk = [model '/Demux'];
    pvDouble = [model '/M0A PWM Vector Double'];
    assert(isBlock(demuxBlk) && isBlock(pvDouble), ...
        'air:M2:FanoutMissing', 'pwm fanout blocks missing.');

    % pre-install backup (restored by the catch block on any failure)
    if ~exist(cfgDir, 'dir')
        mkdir(cfgDir);
    end
    backupFile = fullfile(cfgDir, 'air_spare_pre_m2.slx');
    close_system(model, 0);
    copyfile(fullfile(modelDir, [model '.slx']), backupFile);
    load_system(fullfile(modelDir, [model '.slx']));

    % ---------- 1. capture and delete the Attitude Control out2 branches
    acPh = get_param(ac, 'PortHandles');
    acOut2 = acPh.Outport(2);
    lines = find_system(model, 'FindAll', 'on', 'Type', 'line', ...
        'SrcPortHandle', acOut2);
    assert(numel(lines) == 3, 'air:M2:UnexpectedBranchCount', ...
        'expected 3 branch lines on Attitude Control out 2, got %d.', ...
        numel(lines));
    dstSet = [];
    for j = 1:numel(lines)
        dstSet = [dstSet; get_param(lines(j), 'DstPortHandle')]; %#ok<AGROW>
    end
    dstSet = unique(dstSet);
    demuxIn1 = get_param(demuxBlk, 'PortHandles').Inport(1);
    pvdIn1 = get_param(pvDouble, 'PortHandles').Inport(1);
    assert(numel(dstSet) == 2 && ismember(demuxIn1, dstSet) && ...
        ismember(pvdIn1, dstSet), 'air:M2:UnexpectedConsumers', ...
        'out 2 consumers changed; probe the model before installing.');
    % delete one line at a time and re-query: deleting a branch can
    % invalidate the handles of sibling branch lines
    for iter = 1:10
        lines = find_system(model, 'FindAll', 'on', 'Type', 'line', ...
            'SrcPortHandle', acOut2);
        if isempty(lines)
            break;
        end
        delete_line(lines(1));
    end
    assert(isempty(find_system(model, 'FindAll', 'on', 'Type', 'line', ...
        'SrcPortHandle', acOut2)), 'air:M2:BranchesRemain', ...
        'Attitude Control out 2 still has lines after deletion.');

    % ---------- 2. rpm log-bus source (post-allocator by construction)
    lbIn7 = get_param([model '/M0A Log Bus'], 'PortHandles').Inport(7);
    lbLine = get_param(lbIn7, 'Line');
    assert(lbLine ~= -1, 'air:M2:RpmLineMissing', ...
        'log bus input 7 (rpm) is not wired.');
    rpmSrcPort = get_param(lbLine, 'SrcPortHandle');
    rpmSrc = getfullname(get_param(rpmSrcPort, 'Parent'));
    rpmPortNo = get_param(rpmSrcPort, 'PortNumber');
    assert(contains(rpmSrc, 'RPM'), 'air:M2:RpmSrcUnexpected', ...
        'log bus rpm section fed by %s.', rpmSrc);
    fprintf('M2 rpm source: %s (out %d)\n', rpmSrc, rpmPortNo);

    % ---------- 3. new blocks below the M0-C row ----------
    % all blocks single-output on purpose: Interpreted MATLAB Fcn output
    % port counts are only reliable after compilation, and the half-spliced
    % window between block insertion and re-wiring cannot be compiled at
    % all (the fanout type chain is broken until the allocator feeds back).
    % m2_eta_esc returns [eta_ref; eta_act], m2_alloc_diag returns
    % [sat; dmz]; dedicated Demux blocks split them.
    refPos = get_param([model '/M0C v Ref ESC'], 'Position');
    y0 = refPos(4) + 420;
    x0 = refPos(1);
    add_block('simulink/Sources/Digital Clock', [model '/M2 Clock'], ...
        'Position', [x0 - 320, y0, x0 - 290, y0 + 30], 'SampleTime', '0.05');
    add_block('simulink/Signal Routing/Mux', [model '/M2 ESC Input'], ...
        'Inputs', '9', 'Position', [x0 - 60, y0, x0 - 50, y0 + 300]);
    add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
        [model '/M2 Eta ESC'], ...
        'Position', [x0 + 20, y0 + 100, x0 + 190, y0 + 160], ...
        'MATLABFcn', 'm2_eta_esc', 'OutputDimensions', '2', ...
        'SampleTime', '0.05');
    add_block('simulink/Signal Routing/Demux', [model '/M2 Eta Out Split'], ...
        'Outputs', '2', 'Position', [x0 + 210, y0 + 105, x0 + 215, ...
        y0 + 145]);
    add_block('simulink/Sinks/To Workspace', [model '/M2 Log Eta Bus'], ...
        'VariableName', 'm2_eta_log', ...
        'SaveFormat', get_param([model '/M0A Log P Est'], 'SaveFormat'), ...
        'Position', [x0 + 320, y0 + 570, x0 + 400, y0 + 600]);
    add_block('simulink/Signal Routing/Mux', [model '/M2 Eta Log'], ...
        'Inputs', '4', 'Position', [x0 + 250, y0 + 560, x0 + 260, ...
        y0 + 620]);
    zohDefs = {'M2 PWM ZOH', 'M2 RPM ZOH', 'M2 Sat ZOH', 'M2 Dmz ZOH'};
    zohTs = {'0.05', '0.05', '0.05', '0.05'};
    for k = 1:numel(zohDefs)
        add_block('simulink/Discrete/Zero-Order Hold', ...
            [model '/' zohDefs{k}], ...
            'Position', [x0 - 240, y0 + (k - 1) * 45, x0 - 210, ...
            y0 + (k - 1) * 45 + 30], 'SampleTime', zohTs{k});
    end
    add_block('simulink/Signal Attributes/Data Type Conversion', ...
        [model '/M2 Pwm Conv'], 'OutDataTypeStr', 'double', ...
        'Position', [x0 + 240, y0 + 420, x0 + 290, y0 + 450]);
    add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
        [model '/M2 Eta Allocator'], ...
        'Position', [x0 + 380, y0 + 380, x0 + 550, y0 + 440], ...
        'MATLABFcn', 'm2_eta_allocator', 'OutputDimensions', '8', ...
        'SampleTime', '-1');
    add_block('simulink/Signal Attributes/Data Type Conversion', ...
        [model '/M2 Pwm Uint16'], 'OutDataTypeStr', 'uint16', ...
        'Position', [x0 + 570, y0 + 390, x0 + 620, y0 + 420]);
    add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
        [model '/M2 Alloc Diag'], ...
        'Position', [x0 + 380, y0 + 470, x0 + 550, y0 + 530], ...
        'MATLABFcn', 'm2_alloc_diag', 'OutputDimensions', '2', ...
        'SampleTime', '-1');
    add_block('simulink/Signal Routing/Demux', [model '/M2 Diag Split'], ...
        'Outputs', '2', 'Position', [x0 + 570, y0 + 480, x0 + 575, ...
        y0 + 520]);

    % wiring (single-output blocks only, no intermediate compile needed)
    cp = get_param([model '/M2 Pwm Conv'], 'PortHandles');
    al = get_param([model '/M2 Eta Allocator'], 'PortHandles');
    dg = get_param([model '/M2 Alloc Diag'], 'PortHandles');
    ep = get_param([model '/M2 Eta ESC'], 'PortHandles');
    es = get_param([model '/M2 Eta Out Split'], 'PortHandles');
    ds = get_param([model '/M2 Diag Split'], 'PortHandles');
    lg = get_param([model '/M2 Eta Log'], 'PortHandles');
    add_line(model, acOut2, cp.Inport(1), 'autorouting', 'on');
    add_line(model, cp.Outport(1), al.Inport(1), 'autorouting', 'on');
    add_line(model, cp.Outport(1), dg.Inport(1), 'autorouting', 'on');
    up = get_param([model '/M2 Pwm Uint16'], 'PortHandles');
    add_line(model, al.Outport(1), up.Inport(1), 'autorouting', 'on');
    add_line(model, up.Outport(1), demuxIn1, 'autorouting', 'on');
    add_line(model, up.Outport(1), pvdIn1, 'autorouting', 'on');
    add_line(model, dg.Outport(1), ds.Inport(1), 'autorouting', 'on');
    add_line(model, ds.Outport(1), get_param([model '/M2 Sat ZOH'], ...
        'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, ds.Outport(2), get_param([model '/M2 Dmz ZOH'], ...
        'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, get_param([model '/M2 Clock'], ...
        'PortHandles').Outport(1), get_param([model '/M2 ESC Input'], ...
        'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, ep.Outport(1), es.Inport(1), 'autorouting', 'on');
    add_line(model, es.Outport(1), lg.Inport(1), 'autorouting', 'on');
    add_line(model, es.Outport(2), lg.Inport(2), 'autorouting', 'on');
    add_line(model, get_param([model '/M2 Sat ZOH'], ...
        'PortHandles').Outport(1), lg.Inport(3), 'autorouting', 'on');
    add_line(model, get_param([model '/M2 Dmz ZOH'], ...
        'PortHandles').Outport(1), lg.Inport(4), 'autorouting', 'on');
    add_line(model, lg.Outport(1), get_param([model '/M2 Log Eta Bus'], ...
        'PortHandles').Inport(1), 'autorouting', 'on');
    mip = get_param([model '/M2 ESC Input'], 'PortHandles');
    add_line(model, get_param([model '/M2 Sat ZOH'], ...
        'PortHandles').Outport(1), mip.Inport(9), 'autorouting', 'on');
    % ESC input mux: v/P/E/att/flags branch from the M0-C ZOH outputs
    branchSrc = {'M0C v ZOH', 2; 'M0C P ZOH', 3; 'M0C E ZOH', 4; ...
        'M0C Att ZOH', 5; 'M0C Flags ZOH', 8};
    for k = 1:size(branchSrc, 1)
        sp = get_param(sprintf('%s/%s', model, branchSrc{k, 1}), ...
            'PortHandles');
        add_line(model, sp.Outport(1), mip.Inport(branchSrc{k, 2}), ...
            'autorouting', 'on');
    end
    add_line(model, get_param([model '/M2 PWM ZOH'], ...
        'PortHandles').Outport(1), mip.Inport(6), 'autorouting', 'on');
    add_line(model, get_param([model '/M0A PWM Vector Double'], ...
        'PortHandles').Outport(1), get_param([model '/M2 PWM ZOH'], ...
        'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, get_param([model '/M2 RPM ZOH'], ...
        'PortHandles').Outport(1), mip.Inport(7), 'autorouting', 'on');
    add_line(model, rpmSrcPort, get_param([model '/M2 RPM ZOH'], ...
        'PortHandles').Inport(1), 'autorouting', 'on');
    add_line(model, mip.Outport(1), ep.Inport(1), 'autorouting', 'on');

    % ---------- 4. functional check before saving ----------
    % (a) allocator-alive: fixed eta = 0.9 must reach the rotors (eta_act
    % measured from the post-allocator rpm groups); passthrough would keep
    % eta_act at 1.0 and fail this check
    set_param([model '/M0B Speed Loop Enable'], 'Value', '1');
    set_param([model '/M0A Optimizer Enable'], 'Value', '1');
    M2_ETA_PARAMS = struct('mode', 'fixed', 'center0', 0.9);
    out = sim(model);
    Lg = out.get('m2_eta_log');
    tl = Lg.Time(:);
    Al = double(squeeze(Lg.Data));
    if size(Al, 2) ~= 4
        Al = Al';
    end
    tail = tl >= 6;
    etaActTail = Al(tail, 2);
    fprintf(['func-check (fixed 0.9): eta_act tail mean %.4f ' ...
        'min %.4f max %.4f  sat %.3f  dmz max %.3e\n'], ...
        mean(etaActTail), min(etaActTail), max(etaActTail), ...
        mean(Al(tail, 3)), max(abs(Al(tail, 4))));
    assert(all(isfinite(Al(tail, 2))), 'air:M2:EtaActNaN', ...
        'eta_act not measurable in flight (rotor floor too high?).');
    assert(abs(mean(etaActTail) - 0.9) <= 0.03, ...
        'air:M2:AllocatorNotApplied', ...
        'post-allocator ratio %.4f != commanded 0.9 (passthrough?).', ...
        mean(etaActTail));
    assert(max(abs(Al(tail, 4))) < 0.5, 'air:M2:DmzUnexpected', ...
        'dmz larger than the yaw loop absorbs in the functional check.');
    Mb = out.get('m0b_log_bus');
    tb = Mb.Time;
    Ab = double(squeeze(Mb.Data));
    if size(Ab, 2) ~= 7
        Ab = Ab';
    end
    statusWin = Ab(tb >= 6, 4);
    assert(~any(statusWin >= 3), 'air:M2:SafetyTripped', ...
        'frozen/fallback appeared in the nominal functional check.');
    assert(mean(statusWin == 1 | statusWin == 2) >= 0.95, ...
        'air:M2:NotActive', 'selector not engaged.');

    % (b) identity: defaults (fixed 1.0) must take the passthrough path
    M2_ETA_PARAMS = [];
    out = sim(model);
    Lg = out.get('m2_eta_log');
    Al = double(squeeze(Lg.Data));
    if size(Al, 2) ~= 4
        Al = Al';
    end
    assert(all(Al(:, 1) == 1.0), 'air:M2:IdentityDefault', ...
        'eta_ref with default globals is not identically 1.0.');
    fprintf('func-check (default identity): eta_ref == 1.0 for all samples\n');
    set_param([model '/M0B Speed Loop Enable'], 'Value', '0');
    set_param([model '/M0A Optimizer Enable'], 'Value', '0');
    M2_ETA_PARAMS = [];

    % ---------- 5. re-ensure everything the simulations may have severed,
    % then save ----------
    set_param(model, 'SimulationCommand', 'update');
    ensureAllRoot(model);
    save_system(model);

    % ---------- 6. reload verification of the saved file ----------
    close_system(model, 0);
    load_system(fullfile(modelDir, [model '.slx']));

    acOut2r = get_param(ac, 'PortHandles').Outport(2);
    % re-acquire: handles captured before the backup reload are stale
    demuxIn1 = get_param([model '/Demux'], 'PortHandles').Inport(1);
    pvdIn1 = get_param([model '/M0A PWM Vector Double'], ...
        'PortHandles').Inport(1);
    allocBlk = [model '/M2 Eta Allocator'];
    allocPh = get_param(allocBlk, 'PortHandles');
    L = { ...
        model, 'Attitude Control', 2, 'M2 Pwm Conv', 1; ...
        model, 'M2 Pwm Conv', 1, 'M2 Eta Allocator', 1; ...
        model, 'M2 Pwm Conv', 1, 'M2 Alloc Diag', 1; ...
        model, 'M2 Eta Allocator', 1, 'M2 Pwm Uint16', 1; ...
        model, 'M2 Pwm Uint16', 1, 'Demux', 1; ...
        model, 'M2 Pwm Uint16', 1, 'M0A PWM Vector Double', 1; ...
        model, 'M2 Alloc Diag', 1, 'M2 Diag Split', 1; ...
        model, 'M2 Diag Split', 1, 'M2 Sat ZOH', 1; ...
        model, 'M2 Diag Split', 2, 'M2 Dmz ZOH', 1; ...
        model, 'M2 Clock', 1, 'M2 ESC Input', 1; ...
        model, 'M0C v ZOH', 1, 'M2 ESC Input', 2; ...
        model, 'M0C P ZOH', 1, 'M2 ESC Input', 3; ...
        model, 'M0C E ZOH', 1, 'M2 ESC Input', 4; ...
        model, 'M0C Att ZOH', 1, 'M2 ESC Input', 5; ...
        model, 'M0A PWM Vector Double', 1, 'M2 PWM ZOH', 1; ...
        model, 'M2 PWM ZOH', 1, 'M2 ESC Input', 6; ...
        model, 'M2 RPM ZOH', 1, 'M2 ESC Input', 7; ...
        model, 'M0C Flags ZOH', 1, 'M2 ESC Input', 8; ...
        model, 'M2 Sat ZOH', 1, 'M2 ESC Input', 9; ...
        model, 'M2 ESC Input', 1, 'M2 Eta ESC', 1; ...
        model, 'M2 Eta ESC', 1, 'M2 Eta Out Split', 1; ...
        model, 'M2 Eta Out Split', 1, 'M2 Eta Log', 1; ...
        model, 'M2 Eta Out Split', 2, 'M2 Eta Log', 2; ...
        model, 'M2 Sat ZOH', 1, 'M2 Eta Log', 3; ...
        model, 'M2 Dmz ZOH', 1, 'M2 Eta Log', 4; ...
        model, 'M2 Eta Log', 1, 'M2 Log Eta Bus', 1; ...
        % M0-C interface must be untouched
        model, 'M0C Clock', 1, 'M0C ESC Input', 1; ...
        model, 'M0C ESC Input', 1, 'M0C v Ref ESC', 1; ...
        model, 'M0C v Ref ESC', 1, 'M0B Reference & Safety', 3; ...
        % M0-B safety chain must be untouched (review P1 regression set)
        model, 'M0A Constraint Flags', 1, 'M0B Flags Override', 1; ...
        model, 'M0B Flags Override', 1, 'M0A Log Bus', 8; ...
        model, 'M0B Flags Override', 1, 'M0B Reference & Safety', 4; ...
        model, 'M0B Flags Override', 1, 'M0A Log Constraint Flags', 1; ...
        model, 'M0A Optimizer Enable', 1, 'M0B Reference & Safety', 1; ...
        model, 'M0B v Ref Manual', 1, 'M0B Reference & Safety', 2; ...
        model, 'M0B Ts', 1, 'M0B Reference & Safety', 5; ...
        model, 'M0B Speed Loop Enable', 1, 'M0B Speed Controller', 1; ...
        model, 'M0B v ZOH 1ms', 1, 'M0B Speed Controller', 2; ...
        model, 'M0B Reference & Safety', 1, 'M0B Speed Controller', 4};
    for k = 1:size(L, 1)
        verifyLink(L{k, 1}, L{k, 2}, L{k, 3}, L{k, 4}, L{k, 5});
    end
    % exact source-port-handle assertions for the splice
    l = get_param(get_param([model '/M2 Pwm Conv'], ...
        'PortHandles').Inport(1), 'Line');
    assert(get_param(l, 'SrcPortHandle') == acOut2r, ...
        'air:M2:SpliceSourceMoved', ...
        'M2 Pwm Conv is not fed by Attitude Control out 2.');
    u16ph = get_param([model '/M2 Pwm Uint16'], 'PortHandles');
    l = get_param(demuxIn1, 'Line');
    assert(get_param(l, 'SrcPortHandle') == u16ph.Outport(1), ...
        'air:M2:DemuxSourceWrong', ...
        'Demux in 1 is not fed by the uint16 allocator output.');
    l = get_param(pvdIn1, 'Line');
    assert(get_param(l, 'SrcPortHandle') == u16ph.Outport(1), ...
        'air:M2:LogSourceWrong', ...
        'M0A PWM Vector Double in 1 is not fed by the uint16 output.');
    % the M0-B optimizer placeholder must still be disconnected
    optOut = get_param([model '/M0B v Ref Optimizer'], ...
        'PortHandles').Outport(1);
    assert(get_param(optOut, 'Line') == -1, 'air:M2:ConstantWired', ...
        'M0B v Ref Optimizer is wired after reload.');
    close_system(model, 0);
    fprintf('reload verification: %d critical links intact after save\n', ...
        size(L, 1) + 3);

    % ---------- 7. config archive ----------
    cfgLines = { ...
        "model: air_spare", "stage: M2", ...
        "splice: Attitude Control out2 -> M2 Pwm Conv -> M2 Eta Allocator" ...
        "        -> M2 Pwm Uint16 -> {Demux in1, M0A PWM Vector Double in1}", ...
        "new: M2 Clock, M2 ESC Input (mux 35-wide), M2 Eta ESC (0.05 s),", ...
        "     M2 Eta Out Split, M2 PWM/RPM/Sat/Dmz ZOH, M2 Pwm Conv (double),", ...
        "        (no eta input line: eta reaches the allocator through the", ...
        "        global M2_ETA_APPLIED -- a 0.05->0.004 rate dependency into", ...
        "        the pwm path breaks the bit-exact bypass regression),", ...
        "     M2 Eta Allocator (single out) + M2 Alloc Diag + M2 Diag Split,", ...
        "     M2 Eta Log (mux 4) -> M2 Log Eta Bus (m2_eta_log)", ...
        "esc_input_bus: [t; v; P_est; E_est; att(6); pwm(8); rpm(8);", ...
        "     flags(8); alloc_sat]  (35)", ...
        "eta_path: M2 Eta ESC [eta_ref; eta_act] -> M2 Eta Out Split -> log;", ...
        "kernel: ratioesc.esc_reset/esc_step (modules/ratio_esc, Git module)", ...
        "params: band=[0.75 1.25], amp=0.02, f=0.25 Hz, hp=lp=0.6 rad/s", ...
        "        gain=3.2e-3 (unit-test calibrated), rateLimit=0.05 /s", ...
        "modes: fixed (default, center0=1.0 -> passthrough identity) | esc", ...
        "defaults: speed_loop_enable=0 optimizer_enable=0"};
    writelines(string(cfgLines), fullfile(cfgDir, 'm2_config.txt'));
    cfg = struct('stage', "M2", 'model', "air_spare", ...
        'backup', string(backupFile), 'notes', [cfgLines(3:5)]);
    save(fullfile(cfgDir, 'm2_config.mat'), 'cfg');

    result = struct('model', model, ...
        'allocatorBlock', string(allocBlk), ...
        'backup', string(backupFile), ...
        'configDir', string(cfgDir));
    fprintf('M2 eta allocator PASS: %s\n', model);
    fprintf('Config archived: %s\n', cfgDir);
catch err
    M2_ETA_PARAMS = [];
    if strcmp(dirtyBefore, 'off')
        if bdIsLoaded(model)
            close_system(model, 0);
        end
        if exist(fullfile(cfgDir, 'air_spare_pre_m2.slx'), 'file')
            copyfile(fullfile(cfgDir, 'air_spare_pre_m2.slx'), ...
                fullfile(modelDir, [model '.slx']));
            fprintf('air_spare.slx restored from pre-install backup.\n');
        end
        load_system(fullfile(modelDir, [model '.slx']));
    end
    rethrow(err);
end

% ---------------------------------------------------------------------------
function ensureAllRoot(model)
%ENSUREALLROOT re-add every critical root line until it survives a diagram
%   update (compilation severs lines silently in this environment).
triples = { ...
    'Attitude Control', 2, 'M2 Pwm Conv', 1; ...
    'M2 Pwm Conv', 1, 'M2 Eta Allocator', 1; ...
    'M2 Pwm Conv', 1, 'M2 Alloc Diag', 1; ...
    'M2 Eta Allocator', 1, 'M2 Pwm Uint16', 1; ...
    'M2 Pwm Uint16', 1, 'Demux', 1; ...
    'M2 Pwm Uint16', 1, 'M0A PWM Vector Double', 1; ...
    'M2 Alloc Diag', 1, 'M2 Diag Split', 1; ...
    'M2 Diag Split', 1, 'M2 Sat ZOH', 1; ...
    'M2 Diag Split', 2, 'M2 Dmz ZOH', 1; ...
    'M2 Clock', 1, 'M2 ESC Input', 1; ...
    'M0C v ZOH', 1, 'M2 ESC Input', 2; ...
    'M0C P ZOH', 1, 'M2 ESC Input', 3; ...
    'M0C E ZOH', 1, 'M2 ESC Input', 4; ...
    'M0C Att ZOH', 1, 'M2 ESC Input', 5; ...
    'M0A PWM Vector Double', 1, 'M2 PWM ZOH', 1; ...
    'M2 PWM ZOH', 1, 'M2 ESC Input', 6; ...
    'M2 RPM ZOH', 1, 'M2 ESC Input', 7; ...
    'M0C Flags ZOH', 1, 'M2 ESC Input', 8; ...
    'M2 Sat ZOH', 1, 'M2 ESC Input', 9; ...
    'M2 ESC Input', 1, 'M2 Eta ESC', 1; ...
    'M2 Eta ESC', 1, 'M2 Eta Out Split', 1; ...
    'M2 Eta Out Split', 1, 'M2 Eta Log', 1; ...
    'M2 Eta Out Split', 2, 'M2 Eta Log', 2; ...
    'M2 Sat ZOH', 1, 'M2 Eta Log', 3; ...
    'M2 Dmz ZOH', 1, 'M2 Eta Log', 4; ...
    'M2 Eta Log', 1, 'M2 Log Eta Bus', 1; ...
    'M0B v ZOH 1ms', 1, 'M0C v ZOH', 1; ...
    'M0A Power Measurement', 1, 'M0C P ZOH', 1; ...
    'M0A Power Measurement', 2, 'M0C E ZOH', 1; ...
    'Attitude Control', 3, 'M0C Att ZOH', 1; ...
    'M0B Flags Override', 1, 'M0C Flags ZOH', 1; ...
    'M0C v ZOH', 1, 'M0C ESC Input', 2; ...
    'M0C P ZOH', 1, 'M0C ESC Input', 3; ...
    'M0C E ZOH', 1, 'M0C ESC Input', 4; ...
    'M0C Att ZOH', 1, 'M0C ESC Input', 5; ...
    'M0C Flags ZOH', 1, 'M0C ESC Input', 6; ...
    'M0C Clock', 1, 'M0C ESC Input', 1; ...
    'M0C ESC Input', 1, 'M0C v Ref ESC', 1; ...
    'M0C v Ref ESC', 1, 'M0B Reference & Safety', 3; ...
    'M0A Constraint Flags', 1, 'M0B Flags Override', 1; ...
    'M0B Flags Override', 1, 'M0A Log Bus', 8; ...
    'M0B Flags Override', 1, 'M0B Reference & Safety', 4; ...
    'M0B Flags Override', 1, 'M0A Log Constraint Flags', 1; ...
    'M0A Optimizer Enable', 1, 'M0B Reference & Safety', 1; ...
    'M0B v Ref Manual', 1, 'M0B Reference & Safety', 2; ...
    'M0B Ts', 1, 'M0B Reference & Safety', 5; ...
    'M0B Speed Loop Enable', 1, 'M0B Speed Controller', 1; ...
    'M0B v ZOH 1ms', 1, 'M0B Speed Controller', 2; ...
    'M0B Reference & Safety', 1, 'M0B Speed Controller', 4};
for k = 1:size(triples, 1)
    ensureRootLine(model, triples{k, 1}, triples{k, 2}, ...
        triples{k, 3}, triples{k, 4});
end
end

function ensureRootLine(model, srcName, srcPort, dstName, dstPort)
%ENSUREROOTLINE add model/srcName#srcPort -> model/dstName#dstPort until it
%   survives a diagram update.
    for attempt = 1:6
        dstPh = get_param(sprintf('%s/%s', model, dstName), 'PortHandles');
        l = get_param(dstPh.Inport(dstPort), 'Line');
        if l ~= -1
            srcParent = getfullname(get_param( ...
                get_param(l, 'SrcPortHandle'), 'Parent'));
            if strcmp(srcParent, sprintf('%s/%s', model, srcName))
                return;
            end
            delete_line(l);
        end
        srcPh = get_param(sprintf('%s/%s', model, srcName), 'PortHandles');
        add_line(model, srcPh.Outport(srcPort), dstPh.Inport(dstPort), ...
            'autorouting', 'on');
        try
            set_param(model, 'SimulationCommand', 'update');
        catch e
            if attempt == 6
                rethrow(e);
            end
        end
    end
    error('air:M2:LineUnstable', ...
        'line %s -> %s(in%d) did not survive the diagram update.', ...
        srcName, dstName, dstPort);
end

function verifyLink(sysPath, srcName, srcPort, dstName, dstPort)
%VERIFYLINK assert one saved link: source block, exact source port number
%   and destination (port-handle equality).
    dstPh = get_param(sprintf('%s/%s', sysPath, dstName), 'PortHandles');
    l = get_param(dstPh.Inport(dstPort), 'Line');
    assert(l ~= -1, 'air:M2:LinkMissing', ...
        'link %s -> %s(in%d) missing after reload.', srcName, dstName, dstPort);
    sp = get_param(l, 'SrcPortHandle');
    srcParent = getfullname(get_param(sp, 'Parent'));
    assert(strcmp(srcParent, sprintf('%s/%s', sysPath, srcName)), ...
        'air:M2:LinkWrongSource', ...
        'link into %s(in%d) comes from %s, expected %s.', ...
        dstName, dstPort, srcParent, srcName);
    srcPh = get_param(sprintf('%s/%s', sysPath, srcName), 'PortHandles');
    assert(numel(srcPh.Outport) >= srcPort, 'air:M2:LinkSrcPort', ...
        '%s has fewer than %d outputs.', srcName, srcPort);
    assert(sp == srcPh.Outport(srcPort), 'air:M2:LinkWrongPort', ...
        'link into %s(in%d) uses %s output %d, expected output %d.', ...
        dstName, dstPort, srcName, find(srcPh.Outport == sp), srcPort);
end

function tf = isBlock(path)
try
    get_param(path, 'Handle');
    tf = true;
catch
    tf = false;
end
end
