function [segs, info] = m3_batch_validate(manifest)
%M3_BATCH_VALIDATE Staged-manifest vs source-contract check (rules v1.7
%   section 2 rule 8): the manifest is EVIDENCE, the contract in
%   m3_batch_contract.m is the AUTHORITY. Every consumer (segment entry,
%   aggregate) calls this before trusting the manifest, so raising the
%   attempt cap or editing the declared arm lists in the staged copy is
%   rejected against the committed contract, whatever else was synced.
%   Layout rule (parameterized segmentation): the union of segment arm
%   lists must equal the frozen 14-arm matrix with each arm exactly once,
%   segments are non-empty, and the repro pair (M3-N5/M3-R1) shares ONE
%   segment. Returns segs (name/arms struct array) and info (batchId,
%   gitCommit, maxAttempts).
c = m3_batch_contract();
assert(isstruct(manifest) && isfield(manifest, 'batchId') && ...
    isfield(manifest, 'gitCommit') && isfield(manifest, 'segments') && ...
    isfield(manifest, 'maxAttempts') && isfield(manifest, 'sha'), ...
    'air:M3Batch:ContractMismatch', ...
    'staged manifest is missing required fields (batchId/gitCommit/segments/maxAttempts/sha)');
assert(isa(manifest.batchId, 'char') && numel(manifest.batchId) >= 8, ...
    'air:M3Batch:ContractMismatch', 'manifest batchId is not a usable id');
assert(isscalar(manifest.maxAttempts) && isnumeric(manifest.maxAttempts) && ...
    manifest.maxAttempts == c.maxAttempts, ...
    'air:M3Batch:ContractMismatch', ...
    'manifest maxAttempts %s differs from the frozen contract value %d (a raised cap with synced stamps is exactly the round-9 M2 probe and must die here)', ...
    num2str(manifest.maxAttempts), c.maxAttempts);
n = numel(manifest.segments);
assert(n >= 1, 'air:M3Batch:ContractMismatch', 'empty segment list');
arms = {};
for k = 1:n
    s = manifest.segments(k);
    assert(isfield(s, 'name') && isfield(s, 'arms') && ...
        iscell(s.arms) && ~isempty(s.arms), ...
        'air:M3Batch:ContractMismatch', ...
        'segment %d is malformed (needs a name and a non-empty arm list)', k);
    arms = [arms, s.arms]; %#ok<AGROW>
end
for j = 1:numel(c.arms)
    n = sum(strcmp(arms, c.arms{j}));
    assert(n == 1, 'air:M3Batch:ContractMismatch', ...
        'arm %s appears %d times across the manifest segments -- the frozen matrix requires exactly once (missing/duplicate segments and edited arm lists all fail here)', ...
        c.arms{j}, n);
end
extra = setdiff(arms, c.arms);
assert(isempty(extra), 'air:M3Batch:ContractMismatch', ...
    'arms outside the frozen matrix in the manifest: %s', ...
    strjoin(extra, ','));
[p5, ~] = m3_batch_locate(manifest, c.reproPair{1});
[p1, ~] = m3_batch_locate(manifest, c.reproPair{2});
assert(p5 == p1, 'air:M3Batch:ContractMismatch', ...
    'repro pair %s/%s must share one segment (same-session requirement)', ...
    c.reproPair{1}, c.reproPair{2});
segs = manifest.segments;
info = struct('batchId', manifest.batchId, ...
    'gitCommit', manifest.gitCommit, 'maxAttempts', manifest.maxAttempts);
end
