function result = m3_batch_aggregate(stagedDir)
%M3_BATCH_AGGREGATE Driver-facing aggregate stage (the FORMAL batch
%   entry): resolve the segment archive dirs from the staged done stamps
%   (every manifest segment must have completed -- the batch verdict
%   aggregates exactly the staged evidence), validate the done/result/
%   marker three-way bookkeeping (round-3 Codex report section 3.2: the
%   wrapper used to forward only batchId and archiveDir and drop the rest
%   of the stamp; the six done.attempts classes and every stamp/result/
%   marker inconsistency now die HERE, at the formal entry, before the
%   hardened aggregate runs), and run the aggregate. The new timestamped
%   *_aggregate archive directory is the stage's freshness marker.
S = load(fullfile(stagedDir, 'manifest.mat'), 'manifest');
[segs, ~] = m3_batch_validate(S.manifest);
c = m3_batch_contract();   % the FROZEN cap, never the manifest's word
segDirs = {};
for k = 1:numel(segs)
    f = fullfile(stagedDir, [segs(k).name '.done.mat']);
    assert(exist(f, 'file'), 'air:M3BatchAgg:SegmentNotDone', ...
        'segment %s has no done stamp -- the batch is incomplete', ...
        segs(k).name);
    D = load(f, 'done');
    assert(strcmp(D.done.batchId, S.manifest.batchId), ...
        'air:M3BatchAgg:StampBatchId', ...
        'done stamp of %s carries a foreign batchId', segs(k).name);
    assert(isfield(D.done, 'stage') && ...
        strcmp(D.done.stage, segs(k).name), ...
        'air:M3BatchAgg:StampForeign', ...
        'done stamp of %s is staged for a foreign stage', segs(k).name);
    assert(isfolder(char(D.done.archiveDir)), ...
        'air:M3BatchAgg:ArchiveGone', ...
        'archive %s of segment %s no longer exists', ...
        D.done.archiveDir, segs(k).name);
    validateStampBookkeeping(stagedDir, segs(k).name, D.done, c.maxAttempts);
    segDirs{end + 1} = char(D.done.archiveDir); %#ok<AGROW>
end
result = m3_aggregate_batch(segDirs, stagedDir);
end

% ---------------------------------------------------------------------------
function validateStampBookkeeping(stagedDir, segName, done, cap)
%VALIDATESTAMPBOOKKEEPING done/result/marker three-way consistency
%   (rules section 2 rule 7f, formal-entry ownership per round-3 section
%   3.2): done.attempts must exist, be a finite positive integer within
%   the frozen contract cap, equal the persistent <seg>.attempts marker
%   AND the segment result's attempts; the stamp must carry the result's
%   runId/commit/archiveDir and the bound cfgSha. The inner aggregate
%   re-asserts its side independently (defense in depth), but a tampered
%   STAMP can never reach it.
d = char(done.archiveDir);
f = fullfile(d, 'result.mat');
assert(exist(f, 'file'), 'air:M3BatchAgg:NoResult', ...
    'no result.mat in the stamped archive %s', d);
R = load(f, 'result');
r = R.result;
assert(isfield(done, 'runId') && isfield(r, 'binding') && ...
    isfield(r.binding, 'runId') && strcmp(done.runId, r.binding.runId), ...
    'air:M3BatchAgg:StampIdentity', ...
    'segment %s done.runId does not match its result binding', segName);
assert(isfield(done, 'gitCommit') && isfield(r, 'binding') && ...
    isfield(r.binding, 'gitCommit') && ...
    strcmp(done.gitCommit, r.binding.gitCommit), ...
    'air:M3BatchAgg:StampIdentity', ...
    'segment %s done.gitCommit does not match its result binding', segName);
assert(isfield(r, 'archiveDir') && strcmp(char(r.archiveDir), d), ...
    'air:M3BatchAgg:StampArchive', ...
    'segment %s done.archiveDir does not match its result archiveDir', ...
    segName);
% the six done.attempts rejection classes (missing / 0 / NaN /
% non-integer / over-cap / marker-inconsistent):
assert(isfield(done, 'attempts'), 'air:M3BatchAgg:StampAttempts', ...
    ['segment %s done stamp carries no attempts field -- the missing ' ...
    'stamp field is one of the six rule-7f accounting classes'], segName);
a = done.attempts;
assert(isscalar(a) && isnumeric(a) && isfinite(a) && a > 0 && ...
    a == floor(a), 'air:M3BatchAgg:StampAttempts', ...
    'segment %s done.attempts is 0/NaN/non-integer (got %s)', ...
    segName, num2str(a));
assert(a <= cap, 'air:M3BatchAgg:StampAttempts', ...
    'segment %s done.attempts %d exceeds the frozen contract cap %d', ...
    segName, a, cap);
mk = readMarker(stagedDir, segName);
assert(a == mk, 'air:M3BatchAgg:StampAttempts', ...
    'segment %s done.attempts (%s) inconsistent with the persistent marker (%s)', ...
    segName, num2str(a), num2str(mk));
assert(isfield(r, 'attempts') && isequaln(r.attempts, a), ...
    'air:M3BatchAgg:StampAttempts', ...
    'segment %s result.attempts (%s) inconsistent with done.attempts (%s)', ...
    segName, num2str(r.attempts), num2str(a));
% round-3 section 3.3: the config binding rides the same three-way chain
assert(isfield(done, 'cfgSha') && isfield(r, 'cfgSha') && ...
    strcmp(done.cfgSha, r.cfgSha), 'air:M3BatchAgg:StampConfig', ...
    'segment %s done/result cfgSha mismatch -- config binding not stamped consistently', ...
    segName);
end

function mk = readMarker(stagedDir, segName)
%READMARKER the persistent per-segment counter, hard-failing on any
%   corrupted/missing marker (never rebuilt, never defaulted).
f = fullfile(stagedDir, [segName '.attempts']);
assert(exist(f, 'file'), 'air:M3BatchAgg:StampAttempts', ...
    'persistent attempt marker for segment %s is missing', segName);
raw = strtrim(fileread(f));
mk = str2double(raw);
assert(~isempty(raw) && isfinite(mk) && mk > 0 && mk == floor(mk), ...
    'air:M3BatchAgg:StampAttempts', ...
    'persistent attempt marker for segment %s contains "%s"', ...
    segName, raw);
end
