function result = test_x8phys()
%TEST_X8PHYS Acceptance checks for the X8 motion and energy proxy.
addpath(fileparts(mfilename('fullpath')));
c = x8phys.config();
[state,~] = x8phys.reset(c);

neutral = struct('pwm_us',ones(8,1)*1500, ...
    'wind_ned_mps',zeros(3,1));
[state1,out1] = x8phys.step(state,neutral,0.1,c);
assert_output(out1);
assert(any(abs(state1.rotor_omega_radps-state.rotor_omega_radps)>0), ...
    'x8phys:Test','Rotor execution dynamic did not respond.');
assert(abs(norm(out1.quaternion_bn)-1) < 1e-12, ...
    'x8phys:Test','Quaternion normalization failed.');

% Compare wind and zero-wind power at exactly the same state and rotor RPM.
referenceRpm = 800;
[referenceState,~] = x8phys.reset(c,struct( ...
    'rotor_omega_radps',ones(8,1)*referenceRpm*2*pi/60, ...
    'last_pwm_us',ones(8,1)*1500));
[zeroState,zeroWind] = x8phys.step(referenceState,neutral,0,c);
[windState,windOut] = x8phys.step(referenceState,struct( ...
    'pwm_us',neutral.pwm_us,'wind_ned_mps',[20;0;0]),0,c);
assert(isequal(zeroState,referenceState) && isequal(windState,referenceState), ...
    'x8phys:Test','dt=0 changed object state.');
assert(windOut.electrical_power_W > zeroWind.electrical_power_W && ...
    isequal(windOut.relative_air_velocity_mps,[-20;0;0]), ...
    'x8phys:Test','Wind sign or wind-load power response is invalid.');

% At a common initial state, electrical power must be nondecreasing with PWM.
pwmLevels = [1200 1400 1600 1800];
powerLevels = zeros(size(pwmLevels));
for k = 1:numel(pwmLevels)
    [~,powerOut] = x8phys.step(state,struct( ...
        'pwm_us',ones(8,1)*pwmLevels(k), ...
        'wind_ned_mps',zeros(3,1)),0.05,c);
    powerLevels(k) = powerOut.electrical_power_W;
end
assert(all(diff(powerLevels) >= -1e-10) && any(diff(powerLevels) > 0), ...
    'x8phys:Test','Power is not monotonic with rotor command.');

[~,lowOut] = x8phys.step(state1,struct( ...
    'pwm_us',ones(8,1)*1000,'wind_ned_mps',zeros(3,1)),0.5,c);
[~,highOut] = x8phys.step(state1,struct( ...
    'pwm_us',ones(8,1)*2000,'wind_ned_mps',zeros(3,1)),0.5,c);
assert(lowOut.acceleration_mps2(3)>0 && highOut.acceleration_mps2(3)<0, ...
    'x8phys:Test','PWM command did not change vertical motion direction.');

% Accumulated energy is the exact sum of per-step electrical power integrals.
energyState = state;
energyStart = energyState.energy_electrical_J;
integralJ = 0;
previousSoc = energyState.soc;
for k = 1:25
    command = neutral;
    command.pwm_us(:) = 1250 + 10*k;
    [energyState,energyOut] = x8phys.step(energyState,command,0.02,c);
    integralJ = integralJ + energyOut.energy_step_J;
    assert(energyOut.soc <= previousSoc + 1e-14 && ...
        energyOut.soc >= c.min_soc && energyOut.soc <= c.max_soc, ...
        'x8phys:Test','SOC is not monotonic or left its configured bounds.');
    previousSoc = energyOut.soc;
end
energyError = abs((energyState.energy_electrical_J-energyStart)-integralJ) / ...
    max(integralJ,eps);
assert(energyError <= 1e-6, ...
    'x8phys:Test','Electrical energy integration exceeded the tolerance.');

ocv = c.battery_series * interp1(c.battery_ocv_soc, ...
    c.battery_ocv_cell_V,out1.soc,'linear','extrap');
powerBalanceError = abs(out1.battery_voltage_V*out1.battery_current_A- ...
    out1.electrical_power_W) / max(out1.electrical_power_W,eps);
assert(out1.battery_voltage_V <= ocv + 1e-12 && powerBalanceError <= 1e-12, ...
    'x8phys:Test','Battery OCV/load power balance is invalid.');

% Requested commands are diagnosed while the plant exposes applied commands.
[~,clippedOut] = x8phys.step(state1,struct( ...
    'pwm_us',ones(8,1)*2500,'wind_ned_mps',zeros(3,1)),0.01,c);
assert(clippedOut.constraint_flags(1)==1 && ...
    all(clippedOut.pwm_requested_us==2500) && ...
    all(clippedOut.pwm_applied_us==c.pwm_max_us), ...
    'x8phys:Test','PWM clipping or applied-command reporting failed.');

% Force the Thevenin limit and verify that delivered power remains V*I.
limitedConfig = x8phys.config('cell_resistance_ohm',1, ...
    'battery_resistance_ohm',7);
[limitedState,~] = x8phys.reset(limitedConfig);
[~,limitedOut] = x8phys.step(limitedState,struct( ...
    'pwm_us',ones(8,1)*2000,'wind_ned_mps',zeros(3,1)),1,limitedConfig);
limitedBalanceError = abs(limitedOut.battery_voltage_V* ...
    limitedOut.battery_current_A-limitedOut.electrical_power_W) / ...
    max(limitedOut.electrical_power_W,eps);
assert(limitedOut.object_flags.power_limited && limitedBalanceError <= 1e-12, ...
    'x8phys:Test','Battery power limiting violates terminal power balance.');

% Once cutoff is latched, the next step applies minimum PWM and draws no power.
[cutoffState,~] = x8phys.reset(c,struct('soc',0.01));
[cutoffState,cutoffEvent] = x8phys.step(cutoffState,neutral,0.01,c);
assert(cutoffEvent.object_flags.battery_cutoff, ...
    'x8phys:Test','Low-voltage cutoff was not latched.');
[cutoffState,afterCutoff] = x8phys.step(cutoffState,neutral,0.01,c);
assert(all(afterCutoff.pwm_applied_us==c.pwm_min_us) && ...
    all(cutoffState.last_pwm_us==c.pwm_min_us) && ...
    afterCutoff.electrical_power_W==0 && ...
    afterCutoff.battery_voltage_V<=c.battery_series*interp1( ...
    c.battery_ocv_soc,c.battery_ocv_cell_V,afterCutoff.soc,'linear','extrap')+1e-12, ...
    'x8phys:Test','Cutoff did not force minimum PWM and zero battery power.');

angles = [0.12;-0.08;0.31];
rotationDiff = abs(x8phys.rotation321(angles)- ...
    x8phys.quaternion_rotation(x8phys.euler_to_quaternion(angles)));
assert(max(rotationDiff(:)) < 1e-12, ...
    'x8phys:Test','3-2-1 and quaternion rotations disagree.');
assert_throws(@()x8phys.reset(c,struct('soc',0.5, ...
    'battery_charge_Ah',c.battery_capacity_Ah)),'x8phys:Reset');
assert_throws(@()x8phys.reset(c,struct('quaternion_bn',zeros(4,1))), ...
    'x8phys:Reset');

result = struct('pass',true, ...
    'referenceRpm',referenceRpm, ...
    'zeroWindPower_W',zeroWind.electrical_power_W, ...
    'windPower_W',windOut.electrical_power_W, ...
    'energyRelativeError',energyError, ...
    'powerBalanceRelativeError',powerBalanceError, ...
    'powerLevels_W',powerLevels);
fprintf(['X8PHYS tests PASS: RPM=%.0f P0=%.3f W Pw=%.3f W ' ...
    'energyErr=%.3g balanceErr=%.3g\n'],referenceRpm, ...
    result.zeroWindPower_W,result.windPower_W,energyError,powerBalanceError);
end

function assert_output(out)
assert(numel(out.rotor_thrust_N)==8 && numel(out.pwm_applied_us)==8 && ...
    numel(out.relative_air_velocity_mps)==3 && ...
    all(isfinite([out.position_ned_m;out.velocity_ned_mps; ...
    out.quaternion_bn;out.attitude_rad;out.body_rate_radps; ...
    out.rotor_omega_radps;out.rotor_thrust_N;out.electrical_power_W; ...
    out.battery_voltage_V;out.battery_current_A;out.soc])), ...
    'x8phys:Test','Nominal output dimensions or finite values are invalid.');
end

function assert_throws(fn,identifier)
try
    fn();
    error('x8phys:Test','Expected error %s was not raised.',identifier);
catch err
    assert(strcmp(err.identifier,identifier), ...
        'x8phys:Test','Expected %s, received %s.',identifier,err.identifier);
end
end
