function result = test_x8phys_platform()
%TEST_X8PHYS_PLATFORM Verify the PX4 adapter's causal measurement boundary.
addpath(fileparts(mfilename('fullpath')));
c = x8phys.config();
adapter = x8phys.make_platform_adapter(c);
[state,initialSample] = adapter.reset(struct('soc',0.8));
assert(isstruct(initialSample) && initialSample.t==0 && ...
    isfield(initialSample,'constraint_flags'), ...
    'x8phys:PlatformTest','Adapter reset did not return an initial sample.');
[~,defaultSample] = adapter.reset();
assert(defaultSample.t==0, ...
    'x8phys:PlatformTest','Default adapter reset is not supported.');

platform = struct('motor_pwm_us',ones(8,1)*1500, ...
    'wind_ned_mps',[20;0;0],'v_ref_mps',0);
[state,sample,truth] = adapter.step(state,platform,[],0.1);
required = {'t','v','P_e','E_e','attitude','yaw_rate','motor_pwm', ...
    'motor_rpm','constraint_flags','power_source','voltage_v','current_a', ...
    'soc','valid'};
assert(isequal(sort(fieldnames(sample)),sort(required(:))), ...
    'x8phys:PlatformTest','Adapter exposed missing or private fields.');
assert(isequal(size(sample.attitude),[6 1]) && ...
    isequal(size(sample.motor_pwm),[8 1]) && ...
    isequal(size(sample.motor_rpm),[8 1]) && ...
    isequal(size(sample.constraint_flags),[8 1]), ...
    'x8phys:PlatformTest','M0 measurement dimensions are invalid.');
assert(sample.t==0.1 && sample.P_e>0 && sample.E_e>0 && ...
    sample.power_source==0 && sample.valid && ...
    isequal(sample.motor_pwm,truth.pwm_applied_us), ...
    'x8phys:PlatformTest','Healthy adapter sample is invalid.');

clipped = struct('motor_pwm_us',ones(8,1)*2500, ...
    'wind_ned_mps',zeros(3,1));
[~,bad,badTruth] = adapter.step(state,clipped,[],0.01);
assert(bad.constraint_flags(1)==1 && ~bad.valid && ...
    all(bad.motor_pwm==c.pwm_max_us) && ...
    isequal(bad.motor_pwm,badTruth.pwm_applied_us), ...
    'x8phys:PlatformTest','Applied PWM constraint was not propagated.');

corruptState = state;
corruptState.energy_electrical_J = NaN;
[~,nonfinite] = adapter.step(corruptState,platform,[],0);
assert(nonfinite.constraint_flags(7)==1 && ~nonfinite.valid, ...
    'x8phys:PlatformTest','Nonfinite measurement was not invalidated.');

result = struct('pass',true,'initialSoc',initialSample.soc, ...
    'power_W',sample.P_e,'energy_J',sample.E_e, ...
    'wind_mps',norm(platform.wind_ned_mps));
fprintf('X8PHYS platform PASS: P=%.3f W E=%.3f J flags=%s\n', ...
    result.power_W,result.energy_J,mat2str(sample.constraint_flags'));
end
