% Write the M0-A scenario configuration archive (companion to
% add_air_m0a_constraints_and_logbus; separated after the config write step
% failed post-save in batch mode).
stamp = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
modelDir = fileparts(mfilename('fullpath'));
cfgDir = fullfile(modelDir, 'results', 'm0a_config', stamp);
if ~exist(cfgDir, 'dir')
    mkdir(cfgDir);
end
cfg = struct( ...
    'model', 'air_spare', ...
    'stage', 'M0-A', ...
    'optimizer_enable', 0, ...
    'power_source', 'estimated (flag 0, uncalibrated)', ...
    'solverStep_s', 0.001, ...
    'stopTime_s', 10, ...
    'busLayout', '[v, P_est, E_est, power_source, att(6)=phi theta psi p q r, pwm(8), rpm_est(8), flags(8), optimizer_enable]', ...
    'flagThresholds', struct('att_tol_rad', 0.523, 'yaw_rate_tol_rad_s', 1.5, ...
        'speed_tol_mps', 1.0, 'P_max_W', 1500.0, 'pwm_edge_us', 5.0), ...
    'notes', 'v_ref placeholder = 0 until M0-B; thresholds uncalibrated');
save(fullfile(cfgDir, 'm0a_scenario_config.mat'), 'cfg');
writelines([ ...
    "model: air_spare"
    "stage: M0-A"
    "optimizer_enable: 0"
    "power_source: estimated (flag 0, uncalibrated)"
    "solver_step_s: 0.001"
    "stop_time_s: 10"
    "bus_layout: [v, P_est, E_est, power_source, att(6)=phi theta psi p q r, pwm(8), rpm_est(8), flags(8), optimizer_enable]"
    "flag_thresholds: att_tol_rad=0.523 yaw_rate_tol_rad_s=1.5 speed_tol_mps=1.0 P_max_W=1500 pwm_edge_us=5"
    "notes: v_ref placeholder = 0 until M0-B; thresholds uncalibrated"], ...
    fullfile(cfgDir, 'm0a_scenario_config.txt'));
fprintf('CFG_WRITTEN: %s\n', cfgDir);
