%START_HERE 任务1入口：平移曲线上的瞬时跳变黑箱搜索。
% 从任意 MATLAB 当前目录运行本文件均可。
root=fileparts(mfilename('fullpath')); addpath(root);
% 环境自愈(2026-09-01诊断)：本机R2022b工具箱缓存toolbox_cache-*.xml
% 周期性损坏，损坏期间本目录"快照之后新建的.m"(如launch_task1_demo.m)
% 对which不可见(dir可见、旧文件正常)，删除缓存文件后恢复。这里兜底：
% 解析失败时复制到全新ASCII暂存目录运行，不阻塞演示。
if isempty(which('launch_task1_demo'))
    stage=fullfile(tempdir,'task1_stage');
    if exist(stage,'dir'), rmdir(stage,'s'); end
    mkdir(stage);
    copyfile(fullfile(root,'+task1'),fullfile(stage,'+task1'));
    copyfile(fullfile(root,'launch_task1_demo.m'),stage);
    addpath(stage); rehash;
    fprintf('已启用暂存目录兜底: %s\n',stage);
end
fprintf(['\n== 任务1：平移曲线 + 瞬时跳变黑箱速度搜索 ==\n' ...
    '推荐方案: tracker = Brent混合搜索 + 锁定 + 平移监测重夹逼\n' ...
    '  1) launch_task1_demo   动画面板(播放/暂停/重置, 算法/场景/曲线在线切换,\n' ...
    '                         可导出PNG与GIF动画)\n' ...
    '  2) run_task1_acceptance  单元测试 + 算法横评验收(report.md)\n' ...
    '  3) demo_task1            静态四联图(results/task1/task1_demo.png)\n' ...
    '  4) tests_task1           16项单元测试\n' ...
    '搜索能耗开关: task1.config(''energyAccounting'',true/false)\n' ...
    '  开=把寻优过程能量计入验收(续航纪录口径); 关=只看定位与稳态指标\n' ...
    '  面板右下角图随开关切换: 累计能耗曲线 <-> 估计误差曲线(不重跑仿真)\n' ...
    '核心特性(2026-09-01更新):\n' ...
    '  - 黑箱假设: 不预设最优点, 只给定初始速度, 由搜索器自动找出最优\n' ...
    '  - 多次跳变: 场景选"manual"后点"+ 添加跳变"可加多组 dx/dy/时间\n' ...
    '  - 日志区: 左侧下半部分实时显示跳变、初始搜索、重搜、稳态等关键事件\n\n']);
launch_task1_demo;
