%START_HERE 统一速度寻优程序入口：任务1平移 × 任务2崎岖 × MOP/MOE。
root=fileparts(mfilename('fullpath')); addpath(root);
fprintf(['\n== 统一速度寻优：平移×崎岖×MOP/MOE ==\n' ...
    '推荐算法: ea_multistart(能耗感知) = 局部优先 + 远点证据升级\n' ...
    '          + 对称顶点无偏定位 + 事件驱动平移监测\n' ...
    '  1) launch_unified_demo   动画面板(算法/场景/平移参数在线可调)\n' ...
    '  2) run_unified_acceptance  验收(13测试+8门槛+1小时MOE横比)\n' ...
    '  3) tests_unified / qa_unified_demo\n' ...
    'MOP/MOE: MOE_energy=Emin/E_actual(1小时窗), 7项MOP\n' ...
    '搜索能耗开关: usearch.config(''energyAccounting'',true/false)\n\n']);
launch_unified_demo;
