function result = test_plane_p0p4()
%TEST_PLANE_P0P4 Interface, wind, dynamics, power, and battery checks.
addpath(fileparts(mfilename('fullpath')));
c = plane.config();
[state,resetOut] = plane.reset(c);
assert(resetOut.time_s==0 && strcmp(resetOut.power_source,'proxy') && ...
    strcmp(resetOut.power_model_id,c.power_model_id), ...
    'plane:Test','Reset contract or evidence source failed.');

wind0 = struct('wind_truth_ne_mps',[0;0], ...
    'wind_measured_ne_mps',[9;0],'wind_valid',false);
path0 = struct('time_s',0,'trajectory_type','straight', ...
    'circle_center_ne_m',[NaN;NaN],'circle_radius_m',NaN, ...
    'path_phase_rad',0,'path_tangent_ne',[1;0], ...
    'path_normal_ne',[0;1],'path_valid',true);
command = struct('v_ref_applied_mps',10,'eta_ref_applied',1.2, ...
    'controller_mode','fixed');
[state1,out1] = plane.step(state,wind0,path0,command,0.1,c);
assert(out1.tangential_ground_speed_mps<=c.speed_rate_mps2*0.1+1e-12 && ...
    abs(out1.eta_actual-1)<=c.eta_rate_s*0.1+1e-12, ...
    'plane:Test','Speed or eta execution dynamics exceeded rate limits.');
assert(isequal(out1.air_velocity_ne_mps,out1.ground_velocity_ne_mps), ...
    'plane:Test','Physical state incorrectly used measured wind.');

wind5 = wind0;
wind5.wind_truth_ne_mps = [5;0];
[sameState,windOut] = plane.step(state1,wind5,path0,command,0,c);
assert(isequal(sameState,state1) && ...
    abs(windOut.air_velocity_ne_mps(1)- ...
    (windOut.ground_velocity_ne_mps(1)-5))<1e-12 && ...
    windOut.power_w~=out1.power_w, ...
    'plane:Test','Wind sign, dt=0, or wind-power coupling failed.');

circlePath = path0;
circlePath.trajectory_type = 'circle';
circlePath.circle_center_ne_m = [0;0];
circlePath.circle_radius_m = c.circle_radius_m;
[~,circleOut] = plane.step(state1,wind0,circlePath,command,0,c);
expectedAcceleration = state1.v_ground_mps^2/c.circle_radius_m;
assert(abs(circleOut.centripetal_acceleration_mps2-expectedAcceleration)<1e-12 && ...
    abs(circleOut.body_rate_rpy_radps(3)- ...
    state1.v_ground_mps/c.circle_radius_m)<1e-12 && ...
    abs(circleOut.attitude_rpy_rad(1))>0, ...
    'plane:Test','Circular acceleration, yaw rate, or bank proxy failed.');

[circleState,~] = plane.reset(c,struct('v_ground_mps',5, ...
    'v_ref_mps',5,'eta_actual',1,'eta_ref',1));
circleCommand = struct('v_ref_applied_mps',5,'eta_ref_applied',1, ...
    'controller_mode','fixed');
circlePath.path_tangent_ne = [0;1];
circlePath.path_normal_ne = [-1;0];
circlePeriod = 2*pi*c.circle_radius_m/5;
[circleState,fullCircle] = plane.step(circleState,wind0,circlePath, ...
    circleCommand,circlePeriod,c);
assert(abs(fullCircle.path_phase_rad)<1e-12 && ...
    norm(circleState.position_ne_m-[c.circle_radius_m;0])<1e-10 && ...
    abs(fullCircle.radial_error_m)<1e-10, ...
    'plane:Test','Fixed-radius full-circle phase closure failed.');

energyState = state;
previousSoc = energyState.soc;
integralJ = 0;
for k = 1:20
    [energyState,energyOut] = plane.step(energyState,wind0,path0,command,0.05,c);
    integralJ = integralJ + energyOut.power_w*0.05;
    assert(energyOut.soc<=previousSoc+1e-14 && ...
        energyOut.soc>=0 && energyOut.soc<=1, ...
        'plane:Test','SOC did not decrease monotonically within [0,1].');
    previousSoc = energyOut.soc;
end
energyError = abs(energyState.energy_electrical_J-integralJ)/max(integralJ,eps);
assert(energyError<=1e-6, ...
    'plane:Test','Plane energy integration exceeded tolerance.');

limitedConfig = plane.config('battery_resistance_ohm',10);
[limitedState,~] = plane.reset(limitedConfig);
[~,limitedOut] = plane.step(limitedState,wind0,path0,command,0.1,limitedConfig);
balanceError = abs(limitedOut.voltage_v*limitedOut.current_a- ...
    limitedOut.power_w)/max(limitedOut.power_w,eps);
assert(limitedOut.constraint_flags.power_anomaly && ...
    limitedOut.power_w<limitedOut.power_demand_w && balanceError<=1e-12, ...
    'plane:Test','Plane battery power limiting violates power balance.');

result = struct('pass',true,'zeroWindPower_W',out1.power_w, ...
    'windPower_W',windOut.power_w,'energy_Wh',energyOut.energy_electrical_Wh, ...
    'energyRelativeError',energyError,'powerBalanceRelativeError',balanceError);
fprintf(['PLANE P0-P4 PASS: P0=%.3f W Pw=%.3f W ' ...
    'E=%.6f Wh energyErr=%.3g\n'],result.zeroWindPower_W, ...
    result.windPower_W,result.energy_Wh,result.energyRelativeError);
end
