function c = config(varargin)
%CONFIG Task-2 settings: rugged multimodal debug curve + noise, no shifts.
% 全部为算法与评价侧参数；曲线崎岖项与噪声属于对象真值(power_map/make_plant)，
% 控制器侧白名单见 controller_config.m。
%
% 基准曲线固定为调试二次曲线(与 +speedesc 一致): J0(v)=1+0.003(v-6)^2。
% 崎岖项两个正弦分量(幅值/波长/相位可调, 无平移):
%   P(v) = J0(v) + A1 sin(2πv/λ1+φ1) + A2 sin(2πv/λ2+φ2)
% 默认相位使崎岖项在 v=6 处导数为零(全局最优关于基准最优近似对称分布)。
%
% energyAccounting 是"是否考虑搜索能耗"的开关(沿用任务1口径)：
%   true  = 计入寻优过程能量用于评分与验收(续航纪录口径)；
%   false = 只评价定位精度与稳态指标，能耗列记 NaN。
c=struct('lower',0,'upper',20,'optimum0',6,...
    'rippleA1',0.022,'rippleL1',6.0,'rippleF1',pi,...
    'rippleA2',0.012,'rippleL2',2.0,'rippleF2',pi,...
    'noiseSigma',0.01,'impulse',false,'impulseRate',0.03,'impulseSize',0.10,...
    'tEval',1.0,'duration',400,'tol',0.02,'maxSearchEval',60,'eps',0.35,...
    'scanN',61,'filterMethod','sg','filterW',7,...
    'K',5,'minSep',1.5,'refineSpan',0.7,'repeats',4,...
    'initialSpeed',10,...
    'escA',0.5,'escOmega',0.5,'escGain',8,'escLpOmega',0.5,'escWindow',7,...
    'gridResolution',0.125,...
    'energyAccounting',true,'tailSteps',60,'seed',1);
assert(mod(nargin,2)==0,'task2:Config','Use name/value pairs.');
for k=1:2:nargin
    key=char(varargin{k}); assert(isfield(c,key),'task2:Config','Unknown setting: %s',key);
    c.(key)=varargin{k+1};
end
assert(any(strcmp(c.filterMethod,{'none','moving','gaussian','median','sg'})),...
    'task2:Config','Unknown filter method.');
assert(islogical(c.energyAccounting) && isscalar(c.energyAccounting),...
    'task2:Config','energyAccounting must be a logical scalar.');
assert(islogical(c.impulse) && isscalar(c.impulse),'task2:Config','impulse must be logical.');
positive={'tEval','duration','tol','maxSearchEval','eps','tailSteps','scanN',...
    'filterW','K','minSep','refineSpan','repeats','initialSpeed',...
    'rippleA1','rippleL1','rippleA2','rippleL2','noiseSigma','impulseRate','impulseSize',...
    'escA','escOmega','escGain','escLpOmega','escWindow','gridResolution'};
for k=1:numel(positive), validateattributes(c.(positive{k}),{'double'},...
    {'scalar','real','finite','nonnegative'}); end
assert(c.lower>=0 && c.upper>c.lower,'task2:Config','Invalid bounds.');
assert(c.optimum0>=c.lower && c.optimum0<=c.upper,'task2:Config','Base optimum outside bounds.');
assert(c.initialSpeed>=c.lower && c.initialSpeed<=c.upper,'task2:Config','Initial speed outside bounds.');
assert(mod(c.filterW,2)==1 && c.filterW>=3,'task2:Config','filterW must be odd and >=3.');
assert(c.scanN>=21 && c.scanN<=2001,'task2:Config','scanN out of range.');
assert(c.K>=1 && c.K<=20,'task2:Config','K out of range.');
assert(c.duration>c.tailSteps+c.scanN,'task2:Config','duration must exceed scanN+tailSteps.');
assert(c.repeats>=1 && c.repeats<=10,'task2:Config','repeats out of range.');
assert(2*c.refineSpan<=c.upper-c.lower,'task2:Config','refineSpan too wide.');
assert(c.escOmega*c.tEval<pi,'task2:Config','ESC dither period must span multiple samples.');
end
