function names = log_names()
names={'time','actualSpeed','appliedReference','nextReference','center','truePower',...
    'measuredPower','pairedSpeed','powerTime','highpass','rawGradient','gradient',...
    'dither','ready','limited','frozen','trueOptimum','optimalPower'};
end
