%START_HERE 环境风场研究模块入口（TASKS_1_5_ROUTE §3-5 交付口径）。
root=fileparts(mfilename('fullpath')); addpath(root);
fprintf(['
== 环境风场研究模块（空速物理调度）==
' ...
    '对象: 圆周盘旋, 空速 u=v·t̂+w, P=P0(|u|), V*=6.3, P*=0.913(仓库三次代理)
' ...
    '交付: 解析调度v*(t) / DP验证 / 最优匀速对照 / 可行性 / 在线风估计
' ...
    '      / 任务4敏感性扫描+带宽准则 / 任务5三档信息结构后悔值对比
' ...
    '结论: 1h窗MOE 已知风1.000 > 在线估计0.974 > 匀速0.964 > 恒飞0.949 > 不知风0.938
' ...
    '  1) launch_wind_demo       三模块面板(调度/风估计/飞机/环境模型)
' ...
    '  2) run_wind_acceptance    验收(8/8门槛, 15/15测试)
' ...
    '  3) tests_wind             单元测试

']);
launch_wind_demo;
