%START_HERE 任务2入口：崎岖多峰曲线上的滤波全局寻优。
root=fileparts(mfilename('fullpath')); addpath(root);
fprintf(['\n== 任务2：崎岖多峰曲线(调试二次曲线+正弦崎岖项)上的滤波全局寻优 ==\n' ...
    '推荐方案: multistart = 扫描 -> Savitzky-Golay滤波选谷 -> pattern search\n' ...
    '          重定位 -> 对称stencil抛物线顶点(无偏定位) -> 锁定\n' ...
    '  1) launch_task2_demo   动画面板(播放/暂停/重置, 初速/噪声/崎岖参数/种子\n' ...
    '                         在线可调, 可导出PNG与GIF动画)\n' ...
    '  2) run_task2_acceptance  单元测试 + 滤波研究 + 消融验收(report.md)\n' ...
    '  3) tests_task2           13项单元测试\n' ...
    '  4) qa_task2_demo         面板自检\n' ...
    '无偏移保证: 滤波零相位 + 滤波只选谷/顶点定位置 + 对称曲线设计\n' ...
    '           + 跨种子偏置门槛(|mean err|<=0.05, 实测-0.04)\n' ...
    '搜索能耗开关: task2.config(''energyAccounting'',true/false)\n' ...
    '  开=把寻优过程能量计入验收(续航纪录口径); 关=只看定位与稳态指标\n\n']);
launch_task2_demo;
